Repository Combodo/iTop, pull requests merged in 2018-11, with the labels that each got.

#13 Dutch translations - iTop 2.6 (core, UI)
  dictionaries/en.dictionary.itop.ui.php
  dictionaries/nl.dictionary.itop.core.php
  dictionaries/nl.dictionary.itop.ui.php
Labels: translation

#14 German translations Release/2.6
  datamodels/2.x/itop-config-mgmt/de.dict.itop-config-mgmt.php
  datamodels/2.x/itop-config/de.dict.itop-config.php
  datamodels/2.x/itop-hub-connector/de.dict.itop-hub-connector.php
  datamodels/2.x/itop-knownerror-mgmt/de.dict.itop-knownerror-mgmt.php
  datamodels/2.x/itop-portal-base/de.dict.itop-portal-base.php
  datamodels/2.x/itop-request-mgmt-itil/de.dict.itop-request-mgmt-itil.php
  datamodels/2.x/itop-request-mgmt/de.dict.itop-request-mgmt.php
  dictionaries/de.dictionary.itop.core.php
  dictionaries/de.dictionary.itop.ui.php
Labels: translation

#9 Deprecated: assert(): Calling assert() with a string argument is deprecated in php 7.2
  core/metamodel.class.php
Labels: core, enhancement

#21 Title field XSS vulnerability solution.
  application/cmdbabstract.class.inc.php
Labels: security
