Repository Combodo/iTop, pull requests merged in 2018-12, with the labels that each got.

#28 Some small typo fixes in German translations
  datamodels/2.x/itop-config/de.dict.itop-config.php
  dictionaries/de.dictionary.itop.ui.php
Labels: translation

#36 Update zh.dictionary.itop.ui.php
  dictionaries/zh.dictionary.itop.ui.php
Labels: translation

#37 Update zh.dict.itop-config-mgmt.php
  datamodels/2.x/itop-config-mgmt/zh.dict.itop-config-mgmt.php
Labels: translation

#35 Show resolution_date in resolved problem details.
  datamodels/2.x/itop-problem-mgmt/datamodel.itop-problem-mgmt.xml
Labels: datamodel

#41 rename chinese translation file from zh.dict*php to zh_cn.dict*php .
  datamodels/2.x/authent-external/zh_cn.dict.authent-external.php
  datamodels/2.x/authent-ldap/zh_cn.dict.authent-ldap.php
  datamodels/2.x/authent-local/zh_cn.dict.authent-local.php
  datamodels/2.x/itop-attachments/zh_cn.dict.itop-attachments.php
  datamodels/2.x/itop-backup/zh_cn.dict.itop-backup.php
  datamodels/2.x/itop-change-mgmt-itil/zh_cn.dict.itop-change-mgmt-itil.php
  datamodels/2.x/itop-change-mgmt/zh_cn.dict.itop-change-mgmt.php
  datamodels/2.x/itop-config-mgmt/zh_cn.dict.itop-config-mgmt.php
  datamodels/2.x/itop-config/zh_cn.dict.itop-config.php
  datamodels/2.x/itop-datacenter-mgmt/zh_cn.dict.itop-datacenter-mgmt.php
  datamodels/2.x/itop-hub-connector/zh_cn.dict.itop-hub-connector.php
  datamodels/2.x/itop-incident-mgmt-itil/zh_cn.dict.itop-incident-mgmt-itil.php
  datamodels/2.x/itop-knownerror-mgmt/zh_cn.dict.itop-knownerror-mgmt.php
  datamodels/2.x/itop-portal-base/zh_cn.dict.itop-portal-base.php
  datamodels/2.x/itop-problem-mgmt/zh_cn.dict.itop-problem-mgmt.php
  datamodels/2.x/itop-request-mgmt-itil/zh_cn.dict.itop-request-mgmt-itil.php
  datamodels/2.x/itop-request-mgmt/zh_cn.dict.itop-request-mgmt.php
  datamodels/2.x/itop-service-mgmt-provider/zh_cn.dict.itop-service-mgmt-provider.php
  datamodels/2.x/itop-service-mgmt/zh_cn.dict.itop-service-mgmt.php
  datamodels/2.x/itop-tickets/zh_cn.dict.itop-tickets.php
  datamodels/2.x/itop-welcome-itil/zh_cn.dict.itop-welcome-itil.php
  dictionaries/zh_cn.dictionary.itop.core.php
  dictionaries/zh_cn.dictionary.itop.ui.php
Labels: translation

#45 🌐 update 2.6 chinese translation and corresponding licences
  datamodels/2.x/authent-external/zh_cn.dict.authent-external.php
  datamodels/2.x/authent-ldap/zh_cn.dict.authent-ldap.php
  datamodels/2.x/authent-local/zh_cn.dict.authent-local.php
  datamodels/2.x/itop-attachments/zh_cn.dict.itop-attachments.php
  datamodels/2.x/itop-backup/zh_cn.dict.itop-backup.php
  datamodels/2.x/itop-change-mgmt-itil/zh_cn.dict.itop-change-mgmt-itil.php
  datamodels/2.x/itop-change-mgmt/zh_cn.dict.itop-change-mgmt.php
  datamodels/2.x/itop-config-mgmt/zh_cn.dict.itop-config-mgmt.php
  datamodels/2.x/itop-config/zh_cn.dict.itop-config.php
  datamodels/2.x/itop-datacenter-mgmt/zh_cn.dict.itop-datacenter-mgmt.php
  datamodels/2.x/itop-endusers-devices/zh.dict.itop-endusers-devices.php
  datamodels/2.x/itop-hub-connector/zh_cn.dict.itop-hub-connector.php
  datamodels/2.x/itop-incident-mgmt-itil/zh_cn.dict.itop-incident-mgmt-itil.php
  datamodels/2.x/itop-knownerror-mgmt/zh_cn.dict.itop-knownerror-mgmt.php
  datamodels/2.x/itop-portal-base/zh_cn.dict.itop-portal-base.php
  datamodels/2.x/itop-problem-mgmt/zh_cn.dict.itop-problem-mgmt.php
  datamodels/2.x/itop-request-mgmt-itil/zh_cn.dict.itop-request-mgmt-itil.php
  datamodels/2.x/itop-request-mgmt/zh_cn.dict.itop-request-mgmt.php
  datamodels/2.x/itop-service-mgmt-provider/zh_cn.dict.itop-service-mgmt-provider.php
  datamodels/2.x/itop-service-mgmt/zh_cn.dict.itop-service-mgmt.php
  datamodels/2.x/itop-tickets/zh_cn.dict.itop-tickets.php
  datamodels/2.x/itop-welcome-itil/zh_cn.dict.itop-welcome-itil.php
  dictionaries/zh_cn.dictionary.itop.core.php
  dictionaries/zh_cn.dictionary.itop.ui.php
Labels: translation

#46 update chinese translation for 2.4 branch
  datamodels/2.x/authent-external/zh_cn.dict.authent-external.php
  datamodels/2.x/authent-ldap/zh_cn.dict.authent-ldap.php
  datamodels/2.x/authent-local/zh_cn.dict.authent-local.php
  datamodels/2.x/itop-attachments/zh_cn.dict.itop-attachments.php
  datamodels/2.x/itop-backup/zh_cn.dict.itop-backup.php
  datamodels/2.x/itop-change-mgmt-itil/zh.dict.itop-change-mgmt-itil.php
  datamodels/2.x/itop-change-mgmt-itil/zh_cn.dict.itop-change-mgmt-itil.php
  datamodels/2.x/itop-change-mgmt/zh_cn.dict.itop-change-mgmt.php
  datamodels/2.x/itop-config-mgmt/zh.dict.itop-config-mgmt.php
  datamodels/2.x/itop-config-mgmt/zh_cn.dict.itop-config-mgmt.php
  datamodels/2.x/itop-config/zh_cn.dict.itop-config.php
  datamodels/2.x/itop-incident-mgmt-itil/zh_cn.dict.itop-incident-mgmt-itil.php
  datamodels/2.x/itop-knownerror-mgmt/zh.dict.itop-knownerror-mgmt.php
  datamodels/2.x/itop-knownerror-mgmt/zh_cn.dict.itop-knownerror-mgmt.php
  datamodels/2.x/itop-portal-base/zh_cn.dict.itop-portal-base.php
  datamodels/2.x/itop-problem-mgmt/en.dict.itop-problem-mgmt.php
  datamodels/2.x/itop-problem-mgmt/zh.dict.itop-problem-mgmt.php
  datamodels/2.x/itop-problem-mgmt/zh_cn.dict.itop-problem-mgmt.php
  datamodels/2.x/itop-request-mgmt-itil/zh_cn.dict.itop-request-mgmt-itil.php
  datamodels/2.x/itop-request-mgmt/en.dict.itop-request-mgmt.php
  datamodels/2.x/itop-request-mgmt/zh_cn.dict.itop-request-mgmt.php
  datamodels/2.x/itop-service-mgmt-provider/en.dict.itop-service-mgmt-provider.php
  datamodels/2.x/itop-service-mgmt-provider/zh_cn.dict.itop-service-mgmt-provider.php
  datamodels/2.x/itop-service-mgmt/zh.dict.itop-service-mgmt.php
  datamodels/2.x/itop-service-mgmt/zh_cn.dict.itop-service-mgmt.php
  datamodels/2.x/itop-tickets/zh.dict.itop-tickets.php
  datamodels/2.x/itop-tickets/zh_cn.dict.itop-tickets.php
  datamodels/2.x/itop-welcome-itil/zh_cn.dict.itop-welcome-itil.php
  dictionaries/zh.dictionary.itop.core.php
  dictionaries/zh.dictionary.itop.ui.php
  dictionaries/zh_cn.dictionary.itop.core.php
  dictionaries/zh_cn.dictionary.itop.ui.php
Labels: translation

#48 :globe_with_meridians: chinese translation improvement for release 2.6
  datamodels/2.x/itop-config-mgmt/zh_cn.dict.itop-config-mgmt.php
  datamodels/2.x/itop-config/zh_cn.dict.itop-config.php
  datamodels/2.x/itop-hub-connector/zh_cn.dict.itop-hub-connector.php
  dictionaries/zh_cn.dictionary.itop.core.php
  dictionaries/zh_cn.dictionary.itop.ui.php
Labels: i18n
