Repository Combodo/iTop, pull requests merged in 2019-03, with the labels that each got.

#58 Secure the server: prevent the users from browsing/getting files from…
  .gitignore
  conf/.htaccess
  conf/index.php
  conf/web.config
Labels: security

#64 Update Person list view
  datamodels/2.x/itop-config-mgmt/datamodel.itop-config-mgmt.xml
Labels: UI, datamodel

#59 :bug: composer.json dependencies correctness
  composer.json
Labels: core

#60 Update cron.cmd
  webservices/cron.cmd
Labels: enhancement

#61 Make setup backup location and name similar as other backups
  setup/setuputils.class.inc.php
  setup/wizardsteps.class.inc.php
Labels: core

#70 🌐 Russian translations for 2.6.1 (rebased on master)
  datamodels/2.x/authent-external/ru.dict.authent-external.php
  datamodels/2.x/authent-ldap/ru.dict.authent-ldap.php
  datamodels/2.x/authent-local/ru.dict.authent-local.php
  datamodels/2.x/itop-attachments/ru.dict.itop-attachments.php
  datamodels/2.x/itop-backup/ru.dict.itop-backup.php
  datamodels/2.x/itop-change-mgmt-itil/ru.dict.itop-change-mgmt-itil.php
  datamodels/2.x/itop-change-mgmt/ru.dict.itop-change-mgmt.php
  datamodels/2.x/itop-config-mgmt/ru.dict.itop-config-mgmt.php
  datamodels/2.x/itop-config/ru.dict.itop-config.php
  datamodels/2.x/itop-datacenter-mgmt/ru.dict.itop-datacenter-mgmt.php
  datamodels/2.x/itop-endusers-devices/ru.dict.itop-endusers-devices.php
  datamodels/2.x/itop-hub-connector/ru.dict.itop-hub-connector.php
  datamodels/2.x/itop-incident-mgmt-itil/ru.dict.itop-incident-mgmt-itil.php
  datamodels/2.x/itop-knownerror-mgmt/ru.dict.itop-knownerror-mgmt.php
  datamodels/2.x/itop-portal-base/ru.dict.itop-portal-base.php
  datamodels/2.x/itop-problem-mgmt/ru.dict.itop-problem-mgmt.php
  datamodels/2.x/itop-request-mgmt-itil/ru.dict.itop-request-mgmt-itil.php
  datamodels/2.x/itop-request-mgmt/ru.dict.itop-request-mgmt.php
  datamodels/2.x/itop-service-mgmt-provider/ru.dict.itop-service-mgmt-provider.php
  datamodels/2.x/itop-service-mgmt/ru.dict.itop-service-mgmt.php
  datamodels/2.x/itop-sla-computation/ru.dict.itop-sla-computation.php
  datamodels/2.x/itop-storage-mgmt/ru.dict.itop-storage-mgmt.php
  datamodels/2.x/itop-tickets/ru.dict.itop-tickets.php
  datamodels/2.x/itop-virtualization-mgmt/ru.dict.itop-virtualization-mgmt.php
  datamodels/2.x/itop-welcome-itil/ru.dict.itop-welcome-itil.php
  dictionaries/ru.dictionary.itop.core.php
  dictionaries/ru.dictionary.itop.ui.php
Labels: i18n
