Repository Combodo/iTop, pull requests merged in 2019-04, with the labels that each got.

#68 :memo: CONTRIBUTING : add a note on datamodel modifications
  CONTRIBUTING.md
Labels: documentation

#56 :sparkles: Add status.php for getting iTop's status
  status.inc.php
  status.php
  test/phpunit.xml.dist
  test/status/StatusIncTest.php
  test/status/StatusTest.php
Labels: enhancement

#76 Add support to optionally mention username in password reset mail
  application/loginwebpage.class.inc.php
Labels: core, enhancement

#81 🐛 N°2182 Fix default usage of iTopMutex when TLS is enabled
  core/mutex.class.inc.php
Labels: bug, core

#80 Fix cron crash when MySQL connection lost
  webservices/cron.php
Labels: bug
