Repository Combodo/iTop, pull requests merged in 2020-07, with the labels that each got.

#149 fix: Typology translation for zh_cn
  datamodels/2.x/itop-config-mgmt/zh_cn.dict.itop-config-mgmt.php
Labels: i18n

#151 N°3171 - Friendly name and obsolescence flag not refreshed
  core/attributedef.class.inc.php
  core/dbobject.class.php
  core/metamodel.class.php
  core/oql/expression.class.inc.php
  datamodels/2.x/itop-config-mgmt/datamodel.itop-config-mgmt.xml
  test/ItopDataTestCase.php
  test/core/DBObjectTest.php
  test/core/ExpressionEvaluateTest.php
  test/core/MetaModelTest.php
Labels: core

#150 Generate lifecycle as SVG
  pages/graphviz.php
Labels: R&D planned, core, enhancement

#153 🌐 Dutch translations: fix use of ITOP_APPLICATION, ITOP_APPLICATION_SHORT
  dictionaries/nl.dictionary.itop.ui.php
Labels: i18n
