Repository Combodo/iTop, pull requests merged in 2020-05, with the labels that each got.

#140 N°2985
  application/utils.inc.php
  datamodels/2.x/itop-backup/ajax.backup.php
  datamodels/2.x/itop-backup/status.php
Labels: security

#125 Update nl.dictionary.itop.ui.php
  .jenkins/configuration/default-environment/unattended_install/unattended_install.php
  CONTRIBUTING.md
  README.md
  application/datatable.class.inc.php
  application/ui.extkeywidget.class.inc.php
  core/dbobject.class.php
  core/email.class.inc.php
  css/light-grey.scss
  datamodels/2.x/itop-portal-base/portal/composer.json
  datamodels/2.x/version.xml
  dictionaries/en.dictionary.itop.ui.php
  dictionaries/nl.dictionary.itop.ui.php
  setup/modelfactory.class.inc.php
  test/core/BulkChangeTest.inc.php
  test/core/DBSearchTest.php
  webservices/rest.php
Labels: R&D planned, i18n, question

#141 Fix duplicate version loading
  setup/extensionsmap.class.inc.php
Labels: core

#139 Deadlock log : log inside a dedicated log file instead of creating an EventIssue object
  core/cmdbsource.class.inc.php
  core/log.class.inc.php
  core/metamodel.class.php
Labels: R&D team review needed, core
