Repository Combodo/iTop, pull requests merged in 2020-09, with the labels that each got.

#134 Enable external classes to use bypass function as well
  application/cmdbabstract.class.inc.php
Labels: API, R&D team review needed

#160 Fix filename headers when downloading
  sources/application/TwigBase/Controller/Controller.php
Labels: bug

#162 N°3287 - Set from display name / label in action email
  core/action.class.inc.php
  core/email.class.inc.php
  dictionaries/cs.dictionary.itop.core.php
  dictionaries/da.dictionary.itop.core.php
  dictionaries/de.dictionary.itop.core.php
  dictionaries/en.dictionary.itop.core.php
  dictionaries/es_cr.dictionary.itop.core.php
  dictionaries/fr.dictionary.itop.core.php
  dictionaries/hu.dictionary.itop.core.php
  dictionaries/it.dictionary.itop.core.php
  dictionaries/ja.dictionary.itop.core.php
  dictionaries/nl.dictionary.itop.core.php
  dictionaries/pt_br.dictionary.itop.core.php
  dictionaries/ru.dictionary.itop.core.php
  dictionaries/sk.dictionary.itop.core.php
  dictionaries/tr.dictionary.itop.core.php
  dictionaries/zh_cn.dictionary.itop.core.php
Labels: R&D planned, enhancement

#157 Synchro cleanup
  synchro/synchro_exec.php
  synchro/synchro_import.php
Labels: R&D team review needed

#163 Cleanup references to Flash
  application/displayblock.class.inc.php
  application/itopwebpage.class.inc.php
  images/charts.swf
  images/charts_library/arno.swf
  images/charts_library/arst.swf
  images/charts_library/brfl.swf
  images/charts_library/brno.swf
  images/charts_library/brst.swf
  images/charts_library/cl3d.swf
  images/charts_library/clfl.swf
  images/charts_library/clno.swf
  images/charts_library/clp3.swf
  images/charts_library/cls3.swf
  images/charts_library/clst.swf
  images/charts_library/cnno.swf
  images/charts_library/lnno.swf
  images/charts_library/mxno.swf
  images/charts_library/pi3d.swf
  images/charts_library/pino.swf
  images/charts_library/pono.swf
  images/charts_library/scno.swf
  images/open-flash-chart.swf
  js/swfobject.js
  pages/UI.php
  pages/navigator.php
Labels: modernization
