Repository Combodo/iTop, pull requests merged in 2020-08, with the labels that each got.

#72 [POC] reduce metamodel serialized size
  core/metamodel.class.php
  test/core/MetaModelTest.php
Labels: Performance, core, datamodel, internal

#65 :zap: Optimize Column load when using api core/get
  core/restservices.class.inc.php
Labels: API, Performance, R&D planned

#159 Fixing PT BR translations
  datamodels/2.x/authent-cas/dictionaries/pt_br.dict.authent-cas.php
  datamodels/2.x/authent-local/dictionaries/pt_br.dict.authent-local.php
  datamodels/2.x/combodo-db-tools/dictionaries/pt_br.dict.combodo-db-tools.php
  datamodels/2.x/itop-attachments/dictionaries/pt_br.dict.itop-attachments.php
  datamodels/2.x/itop-change-mgmt/dictionaries/pt_br.dict.itop-change-mgmt.php
  datamodels/2.x/itop-config-mgmt/dictionaries/pt_br.dict.itop-config-mgmt.php
  datamodels/2.x/itop-config/dictionaries/pt_br.dict.itop-config.php
  datamodels/2.x/itop-core-update/dictionaries/pt_br.dict.itop-core-update.php
  datamodels/2.x/itop-files-information/dictionaries/pt_br.dict.itop-files-information.php
  datamodels/2.x/itop-incident-mgmt-itil/dictionaries/pt_br.dict.itop-incident-mgmt-itil.php
  datamodels/2.x/itop-portal-base/dictionaries/pt_br.dict.itop-portal-base.php
  datamodels/2.x/itop-request-mgmt-itil/dictionaries/pt_br.dict.itop-request-mgmt-itil.php
  datamodels/2.x/itop-request-mgmt/dictionaries/pt_br.dict.itop-request-mgmt.php
  datamodels/2.x/itop-service-mgmt-provider/dictionaries/pt_br.dict.itop-service-mgmt-provider.php
  datamodels/2.x/itop-tickets/dictionaries/pt_br.dict.itop-tickets.php
  dictionaries/pt_br.dictionary.itop.core.php
  dictionaries/pt_br.dictionary.itop.ui.php
Labels: i18n
