Repository Combodo/iTop, pull requests merged in 2020-04, with the labels that each got.

#133 Cleanup documentation
  core/dbobject.class.php
Labels: documentation

#132 Treeview : Combodo implementation of PR #87
  application/ui.extkeywidget.class.inc.php
  css/light-grey.scss
  dictionaries/en.dictionary.itop.ui.php
Labels: UI

#138 Add Russian translations for 2.7.0 (rebased)
  datamodels/2.x/authent-local/ru.dict.authent-local.php
  datamodels/2.x/itop-attachments/ru.dict.itop-attachments.php
  datamodels/2.x/itop-config-mgmt/ru.dict.itop-config-mgmt.php
  datamodels/2.x/itop-core-update/ru.dict.itop-core-update.php
  datamodels/2.x/itop-portal-base/ru.dict.itop-portal-base.php
  dictionaries/ru.dictionary.itop.core.php
Labels: i18n
