Repository Combodo/iTop, pull requests merged in 2020-03, with the labels that each got.

#117 N°2793 Log rotation
  core/config.class.inc.php
  core/log.class.inc.php
  test/core/LogFileNameBuilderTest.php
Labels: core

#123 🌐 Typos in English translation (rebased)
  application/applicationextension.inc.php
  dictionaries/en.dictionary.itop.ui.php
Labels: i18n

#124 :globe_with_meridians: Missing Dutch translations
  datamodels/2.x/itop-config-mgmt/nl.dict.itop-config-mgmt.php
  datamodels/2.x/itop-core-update/nl.dict.itop-core-update.php
  dictionaries/nl.dictionary.itop.core.php
Labels: i18n

#95 Make it possible to add return path for mails
  core/email.class.inc.php
Labels: API, R&D planned

#99 Support array for json_data posted in rest/json service
  webservices/rest.php
Labels: API, R&D planned
