Repository Combodo/iTop, pull requests merged in 2020-12, with the labels that each got.

#168 🎨 Fix the filter icon on Data model page
  pages/schema.php
Labels: question

#178 N°3253 Fix setup crashing on incompatible PHP versions - JS check (based on fullmoon branch)
  core/ormlinkset.class.inc.php
  setup/index.php
  setup/wizard.php
Labels: enhancement, internal

#161 Correctly detect if connection to client is secure
  application/utils.inc.php
  setup/setuppage.class.inc.php
  setup/wizardsteps.class.inc.php
Labels: R&D team review needed, core

#182 🌐 Dutch translations: distinguish between "approval" and "acceptance"
  datamodels/2.x/itop-change-mgmt-itil/nl.dict.itop-change-mgmt-itil.php
Labels: i18n
