Repository Combodo/iTop, pull requests merged in 2020-06, with the labels that each got.

#146 Update Dutch SynchroAttribute::update_policy translation
  dictionaries/nl.dictionary.itop.core.php
Labels: i18n

#147 Add "software requirements" section to README
  README.md
Labels: R&D team review needed, documentation

#143 simplify the readme
  README.md
Labels: documentation, question
