Repository Combodo/iTop, pull requests merged in 2021-12, with the labels that each got.

#224 Feature/dict apcu bug
  core/apc-service.class.inc.php
  core/dict.class.inc.php
  core/log.class.inc.php
  lib/composer/autoload_classmap.php
  lib/composer/autoload_static.php
  test/core/dictApcuTest.php
  test/core/dictTest.php
Labels: bug, internal

#245 N°4498 - Introduce new APIs due to iPageUIExtension deprecation
  application/applicationextension.inc.php
  sources/application/WebPage/iTopWebPage.php
Labels: API, R&D team review needed, internal

#250 :globe_with_meridians: Person Name for chinese user
  datamodels/2.x/itop-structure/dictionaries/zh_cn.dict.itop-structure.php
Labels: translation

#249 N°4515 Fix default validation pattern for AttributeURL
  core/config.class.inc.php
  test/core/AttributeDefTest.inc.php
  test/core/AttributeURLDefaultPattern.php
  test/core/AttributeURLTest.php
Labels: API, internal
