Repository Combodo/iTop, pull requests merged in 2021-04, with the labels that each got.

#188 Integrate the current values present the column into the column defin…
  core/attributedef.class.inc.php
  pages/schema.php
  synchro/synchrodatasource.class.inc.php
Labels: R&D planned, core, enhancement, internal, supportability

#193 N°3731 log deprecated calls
  bootstrap.inc.php
  core/coreexception.class.inc.php
  core/log.class.inc.php
  sources/application/WebPage/WebPage.php
Labels: API, internal

#207 🌐 improved chinese for 3.0
  datamodels/2.x/combodo-db-tools/dictionaries/zh_cn.dict.combodo-db-tools.php
  datamodels/2.x/itop-attachments/dictionaries/zh_cn.dict.itop-attachments.php
  datamodels/2.x/itop-config-mgmt/dictionaries/zh_cn.dict.itop-config-mgmt.php
  datamodels/2.x/itop-core-update/dictionaries/zh_cn.dict.itop-core-update.php
  datamodels/2.x/itop-hub-connector/dictionaries/zh_cn.dict.itop-hub-connector.php
  datamodels/2.x/itop-structure/dictionaries/zh_cn.dict.itop-structure.php
  dictionaries/ui/components/zh_cn.dictionary.itop.datatable.php
  dictionaries/ui/components/zh_cn.dictionary.itop.field.php
  dictionaries/ui/components/zh_cn.dictionary.itop.global-search.php
  dictionaries/ui/components/zh_cn.dictionary.itop.quick-create.php
  dictionaries/ui/layouts/zh_cn.dictionary.itop.activity-panel.php
  dictionaries/ui/layouts/zh_cn.dictionary.itop.navigation-menu.php
  dictionaries/ui/layouts/zh_cn.dictionary.itop.object-details.php
  dictionaries/ui/pages/zh_cn.dictionary.itop.preferences.php
  dictionaries/zh_cn.dictionary.itop.core.php
  dictionaries/zh_cn.dictionary.itop.ui.php
Labels: translation
