Repository Combodo/iTop, pull requests merged in 2021-02, with the labels that each got.

#170 Advanced search: Fix string criterion contains '0' returning all results
  sources/application/search/criterionconversion/criteriontooql.class.inc.php
Labels: OQL, Products team review needed, core

#189 🌐 Dutch translations: fix typo ("aangeapst")
  dictionaries/nl.dictionary.itop.ui.php
Labels: i18n

#191 iTop 3.0.0 badge dashlet : make whole badge clickable
  css/backoffice/components/dashlet/_dashlet-badge.scss
  js/components/dashlet/dashlet-badge.js
  sources/application/UI/Base/Component/Dashlet/DashletBadge.php
  sources/application/UI/Base/Component/Dashlet/DashletContainer.php
  templates/base/components/dashlet/dashlet-badge.html.twig
  templates/base/components/dashlet/dashlet-badge.js.twig
Labels: R&D team review needed, UI, internal

#183 Print data source id in synchro_exec output
  synchro/synchro_exec.php
Labels: enhancement, good first issue, supportability
