Repository Combodo/iTop, pull requests merged in 2021-05, with the labels that each got.

#214 Protect \iApplicationUIExtension::EnumAllowedActions uses
  application/displayblock.class.inc.php
Labels: API, core, internal, supportability

#215 If php memory_limit is lower than 256M, set 256M. If it's greater do …
  application/utils.inc.php
  pages/ajax.render.php
  pages/csvimport.php
  test/application/UtilsTest.php
Labels: R&D planned, bug, good first issue, internal

#199 🌐 Update Dutch dictionaries for 3.0
  dictionaries/nl.dictionary.itop.core.php
  dictionaries/nl.dictionary.itop.model.php
  dictionaries/nl.dictionary.itop.ui.php
  dictionaries/ui/components/nl.dictionary.itop.datatable.php
  dictionaries/ui/components/nl.dictionary.itop.field.php
  dictionaries/ui/components/nl.dictionary.itop.global-search.php
  dictionaries/ui/components/nl.dictionary.itop.quick-create.php
  dictionaries/ui/layouts/nl.dictionary.itop.activity-panel.php
  dictionaries/ui/layouts/nl.dictionary.itop.navigation-menu.php
  dictionaries/ui/layouts/nl.dictionary.itop.object-details.php
  dictionaries/ui/pages/nl.dictionary.itop.errorpage.php
  dictionaries/ui/pages/nl.dictionary.itop.preferences.php
Labels: translation
