Repository Combodo/iTop, pull requests merged in 2021-06, with the labels that each got.

#218 🌐 improved chinese for 2.7
  datamodels/2.x/combodo-db-tools/zh_cn.dict.combodo-db-tools.php
  datamodels/2.x/itop-attachments/zh_cn.dict.itop-attachments.php
  datamodels/2.x/itop-change-mgmt/zh_cn.dict.itop-change-mgmt.php
  datamodels/2.x/itop-config-mgmt/zh_cn.dict.itop-config-mgmt.php
  datamodels/2.x/itop-core-update/zh_cn.dict.itop-core-update.php
  datamodels/2.x/itop-request-mgmt-itil/zh_cn.dict.itop-request-mgmt-itil.php
  dictionaries/zh_cn.dictionary.itop.core.php
  dictionaries/zh_cn.dictionary.itop.ui.php
Labels: translation

#213 Update CONTRIBUTING.md with thanks stickers
  CONTRIBUTING.md
  documentation/contributing-guide/contributing-stickers-side-by-side.png
Labels: documentation, internal

#211 Handle errors when sending large volumes of data in datatable's XHR queries, on server with low `max_input_vars`
  pages/ajax.render.php
Labels: internal, supportability

#190 FAF : setup generates symlinks when run on dev env
  .gitignore
  data/.compilation-symlinks
  data/exclude.txt
  setup/ajax.dataloader.php
  setup/applicationinstaller.class.inc.php
  setup/compiler.class.inc.php
  setup/runtimeenv.class.inc.php
  setup/wizardsteps.class.inc.php
Labels: Setup, enhancement, internal

#209 N°3968 - Fixed mutex being silently released after wait_timeout seconds
  core/mutex.class.inc.php
Labels: API, enhancement, internal

#217 🐛 Decimal values with aggregate functions (dashlet group by)
  application/displayblock.class.inc.php
Labels: Products team review needed, bug, core

#196 Show real next backup date
  datamodels/2.x/itop-backup/dictionaries/en.dict.itop-backup.php
  datamodels/2.x/itop-backup/status.php
Labels: enhancement
