Repository Combodo/iTop, pull requests merged in 2022-09, with the labels that each got.

#309 N°2250 - DisplayObject with ormLinkSet ignore Removed
  application/ui.linkswidget.class.inc.php
  js/linkswidget.js
  sources/Application/UI/Links/Indirect/BlockIndirectLinksEdit/BlockIndirectLinksEdit.php
  templates/application/links/indirect/block-indirect-links-edit/layout.js.twig
Labels: internal

#333 🐛 N°5522 - Fix session storage (breadcrumbs) not cleared on logout
  templates/pages/login/logout.html.twig
Labels: bug

#301 N°5235 - Add tmp dir is writable check in setup
  setup/setuputils.class.inc.php
Labels: enhancement, internal, supportability, Setup

#335 Setup wizard : use the ITOP_APPLICATION constant instead of hardcoded "iTop" string
  setup/wizardsteps.class.inc.php
Labels: bug, translation, internal

#331 N°4947 Fix \EMail::LoadConfig (v2)
  core/email.class.inc.php
  sources/Core/Email/EmailLaminas.php
  sources/Core/Email/EmailSwiftMailer.php
Labels: bug, internal

#332 Feature/5305 csvimport enhancement
  core/bulkchange.class.inc.php
  css/backoffice/pages/_csv-import.scss
  dictionaries/cs.dictionary.itop.ui.php
  dictionaries/da.dictionary.itop.ui.php
  dictionaries/de.dictionary.itop.ui.php
  dictionaries/en.dictionary.itop.ui.php
  dictionaries/es_cr.dictionary.itop.ui.php
  dictionaries/fr.dictionary.itop.ui.php
  dictionaries/hu.dictionary.itop.ui.php
  dictionaries/it.dictionary.itop.ui.php
  dictionaries/ja.dictionary.itop.ui.php
  dictionaries/nl.dictionary.itop.ui.php
  dictionaries/pl.dictionary.itop.ui.php
  dictionaries/pt_br.dictionary.itop.ui.php
  dictionaries/ru.dictionary.itop.ui.php
  dictionaries/sk.dictionary.itop.ui.php
  dictionaries/tr.dictionary.itop.ui.php
  dictionaries/zh_cn.dictionary.itop.ui.php
  pages/csvimport.php
  test/ItopDataTestCase.php
  test/core/BulkChangeExtKeyTest.inc.php
  test/core/BulkChangeTest.inc.php
  test/integration/DictionariesConsistencyTest.php
  test/testlist.inc.php
  test/webservices/ImportTest.inc.php
  webservices/import.php
Labels: enhancement, UI, internal

#337 N°5073 - Implements line actions in a datatable
  application/utils.inc.php
  css/backoffice/components/_datatable.scss
  dictionaries/ui/components/datatable/en.dictionary.itop.datatable.php
  dictionaries/ui/components/datatable/fr.dictionary.itop.datatable.php
  js/dataTables.main.js
  lib/composer/autoload_classmap.php
  lib/composer/autoload_static.php
  lib/composer/installed.php
  sources/Application/UI/Base/Component/DataTable/DataTable.php
  sources/Application/UI/Base/Component/DataTable/DataTableUIBlockFactory.php
  sources/Application/UI/Base/Component/DataTable/StaticTable/FormTable/FormTable.php
  sources/Application/UI/Base/Component/DataTable/StaticTable/StaticTable.php
  sources/Application/UI/Base/Component/DataTable/tTableRowActions.php
  sources/Application/UI/Base/Component/Template/Template.php
  sources/Application/UI/Base/Component/Template/TemplateUIBlockFactory.php
  templates/base/components/datatable/layout.html.twig
  templates/base/components/datatable/layout.ready.js.twig
  templates/base/components/datatable/row-actions/handler.js.twig
  templates/base/components/datatable/static/formtable/layout.html.twig
  templates/base/components/datatable/static/formtable/layout.ready.js.twig
  templates/base/components/datatable/static/layout.html.twig
  templates/base/components/datatable/static/layout.ready.js.twig
  templates/base/components/template/layout.html.twig
Labels: internal
