Repository Combodo/iTop, pull requests merged in 2022-11, with the labels that each got.

#340 :bug: N°5703 - Fix navigation menu drawer under dashlets on Safari
  css/backoffice/_shame.scss
  datamodels/2.x/combodo-backoffice-darkmoon-theme/precompiled-themes/main.css
  datamodels/2.x/itop-structure/precompiled-themes/fullmoon/main.css
  datamodels/2.x/itop-structure/precompiled-themes/test-red/main.css
Labels: bug

#345 N°5681 - Add support for "Ctrl + Enter" and "Meta (Cmd) + Enter" submit on multi-line fields
  application/cmdbabstract.class.inc.php
  datamodels/2.x/itop-portal-base/portal/public/js/portal_form_handler.js
  datamodels/2.x/itop-portal-base/portal/templates/layout.html.twig
  js/ckeditor.on-init.js
  js/layouts/activity-panel/caselog-entry-form.js
Labels: enhancement, UI, internal

#329 N°5704 - Unit tests on XML assembly
  setup/modelfactory.class.inc.php
  test/ItopTestCase.php
  test/setup/ModelFactoryTest.php
Labels: internal, tests

#357 N°5706 - Update polish translations thanks to @DudekArtur !
  datamodels/2.x/authent-local/dictionaries/pl.dict.authent-local.php
  datamodels/2.x/combodo-db-tools/dictionaries/pl.dict.combodo-db-tools.php
  datamodels/2.x/itop-backup/dictionaries/pl.dict.itop-backup.php
  datamodels/2.x/itop-bridge-cmdb-ticket/dictionaries/pl.dict.itop-bridge-cmdb-ticket.php
  datamodels/2.x/itop-change-mgmt-itil/dictionaries/pl.dict.itop-change-mgmt-itil.php
  datamodels/2.x/itop-config-mgmt/dictionaries/pl.dict.itop-config-mgmt.php
  datamodels/2.x/itop-core-update/dictionaries/pl.dict.itop-core-update.php
  datamodels/2.x/itop-files-information/dictionaries/pl.dict.itop-files-information.php
  datamodels/2.x/itop-hub-connector/dictionaries/pl.dict.itop-hub-connector.php
  datamodels/2.x/itop-incident-mgmt-itil/dictionaries/pl.dict.itop-incident-mgmt-itil.php
  datamodels/2.x/itop-portal-base/dictionaries/pl.dict.itop-portal-base.php
  datamodels/2.x/itop-portal/dictionaries/pl.dict.itop-portal.php
  datamodels/2.x/itop-problem-mgmt/dictionaries/pl.dict.itop-problem-mgmt.php
  datamodels/2.x/itop-request-mgmt-itil/dictionaries/pl.dict.itop-request-mgmt-itil.php
  datamodels/2.x/itop-request-mgmt/dictionaries/pl.dict.itop-request-mgmt.php
  datamodels/2.x/itop-structure/dictionaries/pl.dict.itop-structure.php
  datamodels/2.x/itop-themes-compat/pl.dict.itop-themes-compat.php
  datamodels/2.x/itop-tickets/dictionaries/pl.dict.itop-tickets.php
  dictionaries/pl.dictionary.itop.core.php
  dictionaries/pl.dictionary.itop.ui.php
  dictionaries/ui/components/breadcrumbs/pl.dictionary.itop.breadcrumbs.php
  dictionaries/ui/components/datatable/pl.dictionary.itop.datatable.php
  dictionaries/ui/components/field/pl.dictionary.itop.field.php
  dictionaries/ui/components/global-search/pl.dictionary.itop.global-search.php
  dictionaries/ui/components/input/pl.dictionary.itop.input.php
  dictionaries/ui/components/quick-create/pl.dictionary.itop.quick-create.php
  dictionaries/ui/layouts/activity-panel/pl.dictionary.itop.activity-panel.php
  dictionaries/ui/layouts/navigation-menu/pl.dictionary.itop.navigation-menu.php
  dictionaries/ui/layouts/object-details/pl.dictionary.itop.object-details.php
  dictionaries/ui/layouts/page-content/pl.dictionary.itop.page-content.php
  dictionaries/ui/layouts/tab-container/pl.dictionary.itop.tab-container.php
  dictionaries/ui/layouts/ui-content-block/pl.dictionary.itop.ui-content-block.php
  dictionaries/ui/pages/errorpage/pl.dictionary.itop.errorpage.php
  dictionaries/ui/pages/preferences/pl.dictionary.itop.preferences.php
Labels: translation

#349 N°2244 - Fix image attributes not being visible in PDF exports
  core/pdfbulkexport.class.inc.php
Labels: enhancement, internal

#336 N°5758 GDPR consent : apply to all instances containing the Hub connector
  setup/setuputils.class.inc.php
  setup/wizardsteps.class.inc.php
Labels: enhancement, internal

#299 :bug: N°5369 - Fix BrowseBrick tree "opening_target" mode for "self" and "new" values
  datamodels/2.x/itop-portal-base/portal/templates/bricks/browse/mode_tree.html.twig
Labels: bug
