Repository Combodo/iTop, pull requests merged in 2022-04, with the labels that each got.

#229 N°5066 - Clean CMDBSource methods
  core/cmdbsource.class.inc.php
Labels: enhancement, API

#280 N°5090 Setup : improve missing dependencies message
  setup/modulediscovery.class.inc.php
  setup/wizardsteps.class.inc.php
Labels: UI, internal, Setup

#281 N°4998 Fix CSS for AttributeDuration in transition form
  css/light-grey.scss
Labels: UI, internal

#244 N°4919 New 'Launch setup" button for admins
  core/config.class.inc.php
  datamodels/2.x/itop-config/config.php
  datamodels/2.x/itop-core-update/dictionaries/en.dict.itop-core-update.php
  datamodels/2.x/itop-core-update/src/Controller/AjaxController.php
  datamodels/2.x/itop-core-update/src/Controller/UpdateController.php
  datamodels/2.x/itop-core-update/view/SelectUpdateFile.html.twig
  datamodels/2.x/itop-core-update/view/SelectUpdateFile.ready.js.twig
  index.php
  setup/wizardcontroller.class.inc.php
Labels: enhancement, internal, Setup

#192 N°3717 Fix create CMDBChange without any corresponding CMDBChangeOp
  core/cmdbchangeop.class.inc.php
  core/cmdbobject.class.inc.php
  datamodels/2.x/combodo-db-tools/dbtools.php
  test/core/CMDBObjectTest.php
  webservices/cron.php
Labels: enhancement, API, internal
