Repository Combodo/iTop, pull requests merged in 2022-10, with the labels that each got.

#352 N°4703 Add Dutch translations to new origins
  datamodels/2.x/itop-incident-mgmt-itil/dictionaries/nl.dict.itop-incident-mgmt-itil.php
  datamodels/2.x/itop-request-mgmt-itil/dictionaries/nl.dict.itop-request-mgmt-itil.php
  datamodels/2.x/itop-request-mgmt/dictionaries/nl.dict.itop-request-mgmt.php
Labels: translation

#346 N°4798 - Align attribute "description" type for Service class
  datamodels/2.x/itop-service-mgmt-provider/datamodel.itop-service-mgmt-provider.xml
Labels: datamodel, internal

#344 N°5646 - Activity panel: Fix compose button opening log picker menu when only 1 log available
  js/layouts/activity-panel/activity-panel.js
Labels: enhancement, UI, internal
