Repository Combodo/iTop, pull requests merged in 2022-12, with the labels that each got.

#373 Feature/modals - generic modal API
  css/backoffice/components/_datatable.scss
  css/backoffice/components/_modal.scss
  datamodels/2.x/itop-portal-base/portal/public/js/toolbox.js
  dictionaries/ui/components/modal/en.dictionary.itop.modal.php
  dictionaries/ui/components/modal/fr.dictionary.itop.modal.php
  js/dataTables.row-actions.js
  js/dataTables.settings.js
  js/pages/backoffice/toolbox.js
  js/utils.js
  lib/composer/InstalledVersions.php
  lib/composer/autoload_classmap.php
  lib/composer/autoload_static.php
  lib/composer/installed.php
  sources/Application/UI/Base/Component/DataTable/DataTableUIBlockFactory.php
  sources/Application/UI/Base/Component/DataTable/tTableRowActions.php
  sources/Application/UI/Base/Component/Dialog/Dialog.php
  sources/Application/UI/Base/Component/Dialog/DialogUIBlockFactory.php
  sources/Application/UI/Base/Component/Modal/DoNotShowAgainOptionBlock.php
  sources/Application/UI/Base/Component/Template/TemplateUIBlockFactory.php
  sources/Application/UI/Links/Direct/BlockDirectLinksViewTable.php
  sources/Application/UI/Links/Indirect/BlockIndirectLinksViewTable.php
  sources/Application/WebPage/iTopWebPage.php
  templates/base/components/datatable/layout.html.twig
  templates/base/components/datatable/layout.ready.js.twig
  templates/base/components/datatable/row-actions/handler.js.twig
  templates/base/components/datatable/static/formtable/layout.html.twig
  templates/base/components/datatable/static/layout.html.twig
  templates/base/components/dialog/layout.ready.js.twig
  templates/pages/backoffice/itopwebpage/layout.html.twig
Labels: enhancement, UI, internal

#371 :memo: CONTRIBUTING: Improvements
  CONTRIBUTING.md
Labels: documentation, internal

#367 Update .gitignore
  .gitignore
Labels: enhancement

#366 🌐 N°5792 - Fix typo in dutch translations
  dictionaries/nl.dictionary.itop.core.php
Labels: translation

#372 :memo: SECURITY: Add disclose policy
  SECURITY.md
Labels: documentation, internal

#338 N°5797 - Email: Fix wrong config load
  sources/Core/Email/EmailLaminas.php
  sources/Core/Email/EmailSwiftMailer.php
Labels: bug, internal

#374 N°5765 - Setup: Never cache folder permissions test response
  setup/setup.js
Labels: bug, internal, Setup

#351 N°2013 - Setup: Cannot execute if existing config file contains an inaccessible MySQL server
  setup/wizardsteps.class.inc.php
Labels: bug, Setup

#368 N°5793 - HTML Sanitizer: Allow 'start' attribute in 'ol' tag
  core/htmlsanitizer.class.inc.php
  test/core/sanitizer/HTMLDOMSanitizerTest.php
Labels: enhancement

#380 N°4852 - Navigation menu: Display "+" dict entries as a tooltip on sub-nodes
  application/menunode.class.inc.php
  templates/base/layouts/navigation-menu/menu-node.html.twig
Labels: enhancement, core, internal
