Repository Combodo/iTop, pull requests merged in 2022-01, with the labels that each got.

#251 ♻️ N°4527 Cleanup `utils::GetImageSize`
  application/utils.inc.php
Labels: modernization

#255 :bulb: Document versions constants
  core/config.class.inc.php
  setup/itopdesignformat.class.inc.php
Labels: API, internal

#221 N°3863 - exec.php : allow subdirectories in the page parameter
  pages/exec.php
Labels: API, internal

#256 N°4652 Better error message when XML node define fails from delta
  setup/modelfactory.class.inc.php
Labels: enhancement, core, Products team review needed, R&D team review needed, Setup

#257 :bug: N°4665 - Fix notice in logs when uploading an SVG image in an AttributeImage
  application/cmdbabstract.class.inc.php
Labels: bug

#231 Properly init objects array
  core/restservices.class.inc.php
Labels: bug
