Repository Combodo/iTop, pull requests merged in 2022-08, with the labels that each got.

#318 N°3390 - Cleanup "debug" param remains by moving logs to debug level / portal channel
  datamodels/2.x/itop-portal-base/portal/src/Controller/AggregatePageBrickController.class.inc.php
  datamodels/2.x/itop-portal-base/portal/src/Helper/SecurityHelper.php
  datamodels/2.x/itop-portal-base/portal/templates/layout.html.twig
Labels: internal

#322 N°4792 - memory limit is reached when an AttributeExternalKey is pointing to a class with an AttributeBlob
  application/ui.extkeywidget.class.inc.php
  core/dbsearch.class.php
Labels: internal

#323 N°5375 - XML custo on Semantic field with hierarchy, breaks at compilation
  setup/compiler.class.inc.php
Labels: bug, internal, Setup

#312 N°5343 - Avoid crash when 1st level menu group is not actually a MenuGroup
  application/menunode.class.inc.php
Labels: bug, internal

#290 N°5135 - Impersonate: history of changes versus log entries
  core/attributedef.class.inc.php
  core/cmdbobject.class.inc.php
  core/userrights.class.inc.php
  test/core/CMDBObjectTest.php
Labels: core, API, internal, modernization

#262 🌐 N°5397 - Updated Dutch translations
  datamodels/2.x/authent-cas/dictionaries/nl.dict.authent-cas.php
  datamodels/2.x/authent-external/dictionaries/nl.dict.authent-external.php
  datamodels/2.x/authent-ldap/dictionaries/nl.dict.authent-ldap.php
  datamodels/2.x/authent-local/dictionaries/nl.dict.authent-local.php
  datamodels/2.x/combodo-backoffice-darkmoon-theme/dictionaries/nl.dict.combodo-backoffice-darkmoon-theme.php
  datamodels/2.x/combodo-db-tools/dictionaries/nl.dict.combodo-db-tools.php
  datamodels/2.x/itop-attachments/dictionaries/nl.dict.itop-attachments.php
  datamodels/2.x/itop-backup/dictionaries/nl.dict.itop-backup.php
  datamodels/2.x/itop-change-mgmt-itil/dictionaries/nl.dict.itop-change-mgmt-itil.php
  datamodels/2.x/itop-change-mgmt/dictionaries/nl.dict.itop-change-mgmt.php
  datamodels/2.x/itop-config-mgmt/dictionaries/nl.dict.itop-config-mgmt.php
  datamodels/2.x/itop-config/dictionaries/nl.dict.itop-config.php
  datamodels/2.x/itop-core-update/dictionaries/nl.dict.itop-core-update.php
  datamodels/2.x/itop-faq-light/dictionaries/nl.dict.itop-faq-light.php
  datamodels/2.x/itop-files-information/dictionaries/nl.dict.itop-files-information.php
  datamodels/2.x/itop-hub-connector/dictionaries/nl.dict.itop-hub-connector.php
  datamodels/2.x/itop-incident-mgmt-itil/dictionaries/nl.dict.itop-incident-mgmt-itil.php
  datamodels/2.x/itop-knownerror-mgmt/dictionaries/nl.dict.itop-knownerror-mgmt.php
  datamodels/2.x/itop-portal-base/dictionaries/nl.dict.itop-portal-base.php
  datamodels/2.x/itop-problem-mgmt/dictionaries/nl.dict.itop-problem-mgmt.php
  datamodels/2.x/itop-request-mgmt-itil/dictionaries/nl.dict.itop-request-mgmt-itil.php
  datamodels/2.x/itop-request-mgmt/dictionaries/nl.dict.itop-request-mgmt.php
  datamodels/2.x/itop-service-mgmt-provider/dictionaries/nl.dict.itop-service-mgmt-provider.php
  datamodels/2.x/itop-service-mgmt/dictionaries/nl.dict.itop-service-mgmt.php
  datamodels/2.x/itop-structure/dictionaries/nl.dict.itop-structure.php
  datamodels/2.x/itop-tickets/dictionaries/nl.dict.itop-tickets.php
  dictionaries/nl.dictionary.itop.core.php
  dictionaries/nl.dictionary.itop.ui.php
  dictionaries/ui/components/breadcrumbs/nl.dictionary.itop.breadcrumbs.php
  dictionaries/ui/components/datatable/nl.dictionary.itop.datatable.php
  dictionaries/ui/components/input/nl.dictionary.itop.input.php
  dictionaries/ui/layouts/activity-panel/nl.dictionary.itop.activity-panel.php
  dictionaries/ui/layouts/navigation-menu/nl.dictionary.itop.navigation-menu.php
  dictionaries/ui/layouts/object-details/nl.dictionary.itop.object-details.php
  dictionaries/ui/layouts/page-content/nl.dictionary.itop.page-content.php
  dictionaries/ui/layouts/tab-container/nl.dictionary.itop.tab-container.php
  dictionaries/ui/layouts/ui-content-block/nl.dictionary.itop.ui-content-block.php
  dictionaries/ui/pages/preferences/nl.dictionary.itop.preferences.php
Labels: translation

#325 N°3979 - Handle initial values on dependent fields
  js/console_form_handler.js
  js/form_handler.js
  sources/Renderer/Console/FieldRenderer/ConsoleSimpleFieldRenderer.php
Labels: internal

#326 N°5318 - Fix DBObject::CheckValue() messages being HTML encoded when not necessary
  application/cmdbabstract.class.inc.php
  core/coreexception.class.inc.php
  core/dbobject.class.php
  pages/UI.php
Labels: internal

#327 N°5024 - Missing result in search widget for external key
  application/ui.extkeywidget.class.inc.php
  js/search/search_form_criteria_enum.js
  pages/ajax.render.php
Labels: internal

#319 :globe_with_meridians: N°5390 - Update german translations for OAuth client module
  datamodels/2.x/itop-oauth-client/de.dict.itop-oauth-client.php
Labels: translation

#282 Debug log for invalid placeholders
  core/metamodel.class.php
Labels: enhancement, internal, supportability

#297 N°5216 Invalid message-id when sending notification using cron on system with a specific locale set
  core/action.class.inc.php
Labels: bug, internal

#334 N°5085 - Move menu is impossible - Error after compilation
  setup/compiler.class.inc.php
Labels: internal
