Repository Combodo/iTop, pull requests merged in 2022-03, with the labels that each got.

#271 N°4920 - Fix "undefined index" notice in user rights
  addons/userrights/userrightsprofile.class.inc.php
Labels: bug, core, internal

#270 N°4816 - Fix broken setup on fresh install with existing configuration file
  sources/application/WebPage/WebPage.php
Labels: bug, Setup

#273 N°4921 - Add support for attcode & attvalue parameters in URL to access an object
  core/metamodel.class.php
  datamodels/2.x/itop-portal-base/portal/config/routes/object_brick.yaml
  datamodels/2.x/itop-portal-base/portal/src/Controller/ObjectController.php
  pages/UI.php
Labels: enhancement, core, internal

#275 N°4849 - Enable notification emails grouping in threads in email clients
  core/action.class.inc.php
  core/email.class.inc.php
  core/log.class.inc.php
  test/core/ActionEmailTest.php
Labels: enhancement, internal

#277 Improve German translation
  datamodels/2.x/authent-external/dictionaries/de.dict.authent-external.php
  datamodels/2.x/authent-local/dictionaries/de.dict.authent-local.php
  datamodels/2.x/combodo-backoffice-darkmoon-theme/dictionaries/de.dict.combodo-backoffice-darkmoon-theme.php
  datamodels/2.x/combodo-db-tools/dictionaries/de.dict.combodo-db-tools.php
  datamodels/2.x/itop-backup/dictionaries/de.dict.itop-backup.php
  datamodels/2.x/itop-change-mgmt/dictionaries/de.dict.itop-change-mgmt.php
  datamodels/2.x/itop-config-mgmt/dictionaries/de.dict.itop-config-mgmt.php
  datamodels/2.x/itop-core-update/dictionaries/de.dict.itop-core-update.php
  datamodels/2.x/itop-request-mgmt-itil/dictionaries/de.dict.itop-request-mgmt-itil.php
  datamodels/2.x/itop-request-mgmt/dictionaries/de.dict.itop-request-mgmt.php
  datamodels/2.x/itop-service-mgmt-provider/dictionaries/de.dict.itop-service-mgmt-provider.php
  datamodels/2.x/itop-service-mgmt/dictionaries/de.dict.itop-service-mgmt.php
  datamodels/2.x/itop-structure/dictionaries/de.dict.itop-structure.php
  datamodels/2.x/itop-themes-compat/de.dict.itop-themes-compat.php
  datamodels/2.x/itop-tickets/dictionaries/de.dict.itop-tickets.php
  dictionaries/de.dictionary.itop.core.php
  dictionaries/de.dictionary.itop.ui.php
  dictionaries/ui/components/breadcrumbs/de.dictionary.itop.breadcrumbs.php
  dictionaries/ui/components/datatable/de.dictionary.itop.datatable.php
  dictionaries/ui/components/input/de.dictionary.itop.input.php
  dictionaries/ui/layouts/navigation-menu/de.dictionary.itop.navigation-menu.php
  dictionaries/ui/pages/preferences/de.dictionary.itop.preferences.php
Labels: translation
