Repository Combodo/iTop, pull requests merged in 2022-05, with the labels that each got.

#279 N°5072 - Fix default priority to undefined (null) or default value if not nullable
  datamodels/2.x/itop-incident-mgmt-itil/datamodel.itop-incident-mgmt-itil.xml
  datamodels/2.x/itop-problem-mgmt/datamodel.itop-problem-mgmt.xml
  datamodels/2.x/itop-request-mgmt-itil/datamodel.itop-request-mgmt-itil.xml
  datamodels/2.x/itop-request-mgmt/datamodel.itop-request-mgmt.xml
Labels: enhancement, datamodel, internal

#288 🌐 Add dictionary items for integrity checks
  application/cmdbabstract.class.inc.php
  core/dbobject.class.php
  dictionaries/en.dictionary.itop.core.php
  dictionaries/en.dictionary.itop.ui.php
  pages/UI.php
Labels: translation

#294 N°4872 - Create a ticket in resolved statut Inlineimage disappear
  pages/UI.php
Labels: internal
