Repository Combodo/iTop, pull requests merged in 2023-10, with the labels that each got.

#527 N°5786 - Problem with text color in public log and in AttributeHTML
  css/backoffice/vendors/_bulma-variables-overload.scss
Labels: bug, internal

#496 N°2909 - Search on Enum, Date, TagSet,... with index fails
  js/search/search_form_criteria.js
Labels: internal

#468 N°3715 - Export above 1000 entries ignore obsolete data from user preference
  core/bulkexport.class.inc.php
  tests/php-unit-tests/unitary-tests/core/BulkExportTest.php
Labels: bug, internal

#559 N°6385 - Allow to disable LinkedSet (1:n & n:n) edition by XML
  core/attributedef.class.inc.php
  setup/compiler.class.inc.php
  sources/Application/UI/Links/AbstractBlockLinkSetViewTable.php
  sources/Application/UI/Links/Direct/BlockDirectLinkSetEditTable.php
  sources/Application/UI/Links/Direct/BlockDirectLinkSetViewTable.php
  sources/Application/UI/Links/Indirect/BlockIndirectLinkSetEditTable.php
  sources/Application/UI/Links/Indirect/BlockIndirectLinkSetViewTable.php
Labels: internal

#550 N°6869 - Update chinese translations for ProfilesMenu
  dictionaries/zh_cn.dictionary.itop.ui.php
Labels: good first issue, translation

#552 N°6651 - 3.1 bulk modify n:n like Tagset: checkbox ignored
  js/selectize/plugin_combodo_multi_values_synthesis.js
  js/selectize/plugin_combodo_update_operations.js
  sources/Application/UI/Links/Set/LinksSetUIBlockFactory.php
Labels: internal

#557 N°6849 - Enhance setup error message in case of unmet module dependen…
  setup/modulediscovery.class.inc.php
Labels: enhancement, internal, supportability, Setup

#561 N°6866 - Fix issue when creating new fields in Request Template in French
  sources/application/UI/Base/Component/DataTable/DataTableUIBlockFactory.php
Labels: bug, internal
