Repository Combodo/iTop, pull requests merged in 2023-11, with the labels that each got.

#566 N°6852 - Missing configuration forgot_password_from
  application/loginwebpage.class.inc.php
Labels: internal

#564 N°6887 - Too many OQL requests to execute in order to diplay the grant matrix
  addons/userrights/userrightsprofile.class.inc.php
Labels: internal

#554 N°6954 - Update english translations
  datamodels/2.x/itop-change-mgmt-itil/dictionaries/en.dict.itop-change-mgmt-itil.php
Labels: good first issue, translation

#574 N°6975 ItopCustomDatamodelTestCase VS symlinks flag
  tests/php-unit-tests/src/BaseTestCase/ItopCustomDatamodelTestCase.php
Labels: bug, internal, tests

#568 N°6901 - Enable tracking of iTop active sessions (monitoring)
  application/menunode.class.inc.php
  core/cmdbsource.class.inc.php
  core/config.class.inc.php
  core/log.class.inc.php
  lib/composer/autoload_classmap.php
  lib/composer/autoload_static.php
  pages/ajax.render.php
  sources/Application/Helper/Session.php
  sources/SessionTracker/SessionGC.php
  sources/SessionTracker/SessionHandler.php
  tests/php-unit-tests/unitary-tests/sources/SessionTracker/SessionHandlerTest.php
  webservices/cron.php
Labels: enhancement, core, internal

#473 N°3767 - Impact analysis: Display filtering box on CIs list and groups
  core/displayablegraph.class.inc.php
  datamodels/2.x/itop-config-mgmt/dictionaries/cs.dict.itop-config-mgmt.php
  datamodels/2.x/itop-config-mgmt/dictionaries/da.dict.itop-config-mgmt.php
  datamodels/2.x/itop-config-mgmt/dictionaries/de.dict.itop-config-mgmt.php
  datamodels/2.x/itop-config-mgmt/dictionaries/en.dict.itop-config-mgmt.php
  datamodels/2.x/itop-config-mgmt/dictionaries/es_cr.dict.itop-config-mgmt.php
  datamodels/2.x/itop-config-mgmt/dictionaries/fr.dict.itop-config-mgmt.php
  datamodels/2.x/itop-config-mgmt/dictionaries/hu.dict.itop-config-mgmt.php
  datamodels/2.x/itop-config-mgmt/dictionaries/it.dict.itop-config-mgmt.php
  datamodels/2.x/itop-config-mgmt/dictionaries/ja.dict.itop-config-mgmt.php
  datamodels/2.x/itop-config-mgmt/dictionaries/nl.dict.itop-config-mgmt.php
  datamodels/2.x/itop-config-mgmt/dictionaries/pl.dict.itop-config-mgmt.php
  datamodels/2.x/itop-config-mgmt/dictionaries/pt_br.dict.itop-config-mgmt.php
  datamodels/2.x/itop-config-mgmt/dictionaries/ru.dict.itop-config-mgmt.php
  datamodels/2.x/itop-config-mgmt/dictionaries/sk.dict.itop-config-mgmt.php
  datamodels/2.x/itop-config-mgmt/dictionaries/tr.dict.itop-config-mgmt.php
  datamodels/2.x/itop-config-mgmt/dictionaries/zh_cn.dict.itop-config-mgmt.php
  pages/UI.php
  pages/ajax.render.php
Labels: enhancement, internal

#533 N°3465 - Fix attachment file name hardcoded to "uploaded-file" when imported from CSV import
  application/utils.inc.php
Labels: internal

#576 N°6976 Fix DeprecatedCallsLog error handler never set
  approot.inc.php
  core/log.class.inc.php
  tests/php-unit-tests/src/BaseTestCase/ItopTestCase.php
  tests/php-unit-tests/unitary-tests/core/Log/DeprecatedCallsLogErrorHandlerTest.php
Labels: bug, API, internal, tests

#577 N°6933 - Symfony 6.4 - Remove deprecated calls
  datamodels/2.x/itop-portal-base/portal/src/Controller/AbstractController.php
  datamodels/2.x/itop-portal-base/portal/src/Controller/AggregatePageBrickController.php
  datamodels/2.x/itop-portal-base/portal/src/Controller/BrowseBrickController.php
  datamodels/2.x/itop-portal-base/portal/src/Controller/CreateBrickController.php
  datamodels/2.x/itop-portal-base/portal/src/Controller/ManageBrickController.php
  datamodels/2.x/itop-portal-base/portal/src/Controller/ObjectController.php
  datamodels/2.x/itop-portal-base/portal/src/Controller/SessionMessageController.php
  datamodels/2.x/itop-portal-base/portal/src/Controller/UserProfileBrickController.php
Labels: core, internal, modernization

#537 N°938 - Improve print of portal object page and portal dashboard page
  datamodels/2.x/itop-portal-base/portal/public/css/portal.scss
Labels: internal
