Repository Combodo/iTop, pull requests merged in 2023-03, with the labels that each got.

#448 N°5922 - Fix plus button semantic on ext. key widget
  application/ui.extkeywidget.class.inc.php
  css/backoffice/components/_field.scss
  js/extkeywidget.js
  pages/ajax.render.php
Labels: bug, internal

#447 N°5993 - Add purge mechanism to log system
  core/config.class.inc.php
  core/log.class.inc.php
Labels: internal

#379 N°5784 - PHP 8.0: Fix mandatory attribute not visible in transition form due to bad emptiness test
  application/cmdbabstract.class.inc.php
  core/attributedef.class.inc.php
  core/dbobject.class.php
  tests/php-unit-tests/unitary-tests/core/AttributeDefTest.inc.php
Labels: core, internal

#339 N°6077 - Attachment class: now creation_date and user_id are init by default
  datamodels/2.x/itop-attachments/ajax.itop-attachment.php
  datamodels/2.x/itop-attachments/datamodel.itop-attachments.xml
  datamodels/2.x/itop-portal-base/portal/src/Controller/ObjectController.php
Labels: bug, internal

#359 N°6101 Replace old Ctrl+Enter detection in run_query with the new one
  js/jquery.hotkeys.js
  pages/run_query.php
  tests/php-unit-tests/legacy-tests/VerifyOQL.php
Labels: internal

#311 N°6104 - Fix exception thrown if 'item_class' has 'org_id' attcode mapped to another attcode not present in Person class
  datamodels/2.x/itop-attachments/datamodel.itop-attachments.xml
Labels: bug

#453 N°6105 - Cleanup unnecessary use of dirname(__FILE__)
  application/utils.inc.php
  approot.inc.php
  datamodels/2.x/itop-backup/ajax.backup.php
  datamodels/2.x/itop-backup/backup.php
  datamodels/2.x/itop-backup/common.cli-execution.php
  datamodels/2.x/itop-backup/restore.php
  datamodels/2.x/itop-backup/status.php
  datamodels/2.x/itop-hub-connector/ajax.php
  datamodels/2.x/itop-tickets/module.itop-tickets.php
  index.php
  setup/compiler.class.inc.php
  synchro/priv_sync_chunk.php
  synchro/synchro_exec.php
  synchro/synchro_import.php
  webservices/createfrommail.php
  webservices/cron.php
  webservices/export-v2.php
  webservices/export.php
  webservices/import.php
  webservices/rest.php
Labels: modernization

#461 N°6121 - Update hungarian translations thanks to @tacsaby
  dictionaries/hu.dictionary.itop.core.php
Labels: translation

#465 N°6055 - Fix undefined offset error in synchro_exec.php
  synchro/synchro_import.php
Labels: internal

#471 N°6121 Update hu.dictionary.itop.core.php
  dictionaries/hu.dictionary.itop.core.php
Labels: translation

#456 N°3795 - Replace JS alert native calls with centralized informative modals
  core/displayablegraph.class.inc.php
  js/dashboard.js
  js/extkeywidget.js
  js/forms-json-utils.js
  js/layouts/activity-panel/activity-panel.js
  js/links/links_view_table_widget.js
  js/utils.js
  pages/UI.php
  pages/csvimport.php
  sources/Controller/Base/Layout/ObjectController.php
  sources/Controller/Links/LinksetController.php
  webservices/export-v2.php
Labels: UI, internal

#469 N°5976 - Add modal creation for linksets displayed with tagset-like widget
  application/cmdbabstract.class.inc.php
  css/backoffice/vendors/_selectize.scss
  dictionaries/ui/application/object/en.dictionary.itop.object.php
  js/links/links-set-worker.js
  js/links/links-set.js
  js/links/links_view_table_widget.js
  js/object/object-worker.js
  js/selectize/plugin_combodo_add_button.js
  pages/UI.php
  sources/Application/UI/Base/Component/Input/Set/Set.php
  sources/Application/UI/Links/AbstractBlockLinksViewTable.php
  sources/Application/UI/Links/Set/LinksSetUIBlockFactory.php
  sources/Application/WebPage/iTopWebPage.php
  sources/Controller/Base/Layout/ObjectController.php
  sources/Controller/Links/LinksetController.php
Labels: internal
