Repository Combodo/iTop, pull requests merged in 2023-06, with the labels that each got.

#474 N°6125 - Issue with GetAttributeFlags and GetInitialStateAttributeFlags within iTop 3.0.2
  application/cmdbabstract.class.inc.php
Labels: bug, internal

#306 N°3213 - Order transition attributes like in the "details" zlist instead of reordering them regarding the dependencies
  application/cmdbabstract.class.inc.php
  core/metamodel.class.php
  setup/compiler.class.inc.php
Labels: enhancement, UI, internal

#506 N°918 - Translate placeholders in notifications
  core/action.class.inc.php
  core/attributedef.class.inc.php
  dictionaries/en.dictionary.itop.core.php
  dictionaries/fr.dictionary.itop.core.php
  templates/datamodel/ActionEmail/email-notification-preview.html.twig
  tests/php-unit-tests/unitary-tests/core/ActionEmailTest.php
Labels: internal

#499 🌐 N°6418 - Fix dutch translations on impact relation view
  datamodels/2.x/itop-config-mgmt/dictionaries/nl.dict.itop-config-mgmt.php
Labels: translation

#485 N°6239 - Portail: Fix error message when trying to display object with missing icon
  core/attributedef.class.inc.php
Labels: internal

#458 N°6098 updateLicenses : check availability of the required JQ command
  .make/license/updateLicenses.php
Labels: internal

#265 N°4698 setup/phpinfo.php : when no valid iTop installation, display a comprehensive message instead of an exception
  setup/phpinfo.php
Labels: documentation, internal, supportability, Setup

#466 N°5594 - Dashboard Bug with Group by (table) - iTop 3.0
  sources/Application/UI/Base/Component/DataTable/StaticTable/StaticTable.php
Labels: bug, internal

#494 N°6047 - Make iTop scripts work by HTTP via token with specific scopes
  core/contexttag.class.inc.php
  webservices/export-v2.php
  webservices/export.php
  webservices/import.php
Labels: core, internal

#508 N°6000+6005 - CSV Import with quote no more handled
  application/applicationcontext.class.inc.php
  core/csvbulkexport.class.inc.php
  pages/csvimport.php
Labels: core, internal

#512 N°6468 update zh-cn dict
  datamodels/2.x/itop-config-mgmt/dictionaries/zh_cn.dict.itop-config-mgmt.php
  datamodels/2.x/itop-incident-mgmt-itil/dictionaries/zh_cn.dict.itop-incident-mgmt-itil.php
  datamodels/2.x/itop-portal-base/dictionaries/zh_cn.dict.itop-portal-base.php
  datamodels/2.x/itop-portal/dictionaries/zh_cn.dict.itop-portal.php
  datamodels/2.x/itop-request-mgmt-itil/dictionaries/zh_cn.dict.itop-request-mgmt-itil.php
  datamodels/2.x/itop-request-mgmt/dictionaries/zh_cn.dict.itop-request-mgmt.php
  datamodels/2.x/itop-service-mgmt-provider/dictionaries/zh_cn.dict.itop-service-mgmt-provider.php
  datamodels/2.x/itop-service-mgmt/dictionaries/zh_cn.dict.itop-service-mgmt.php
  datamodels/2.x/itop-structure/dictionaries/zh_cn.dict.itop-structure.php
  dictionaries/ui/layouts/navigation-menu/zh_cn.dictionary.itop.navigation-menu.php
  dictionaries/zh_cn.dictionary.itop.core.php
  dictionaries/zh_cn.dictionary.itop.ui.php
Labels: translation

#498 N°6342 - Fix empty list when configuring a list adding a log attribute
  js/dataTables.settings.js
Labels: internal

#515 N°6476 - Revert datamodel / compiler changes from N°5563
  core/attributedef.class.inc.php
  datamodels/2.x/itop-bridge-cmdb-services/datamodel.itop-bridge-cmdb-services.xml
  datamodels/2.x/itop-bridge-cmdb-ticket/datamodel.itop-bridge-cmdb-ticket.xml
  datamodels/2.x/itop-change-mgmt-itil/datamodel.itop-change-mgmt-itil.xml
  datamodels/2.x/itop-change-mgmt/datamodel.itop-change-mgmt.xml
  datamodels/2.x/itop-config-mgmt/datamodel.itop-config-mgmt.xml
  datamodels/2.x/itop-datacenter-mgmt/datamodel.itop-datacenter-mgmt.xml
  datamodels/2.x/itop-faq-light/datamodel.itop-faq-light.xml
  datamodels/2.x/itop-incident-mgmt-itil/datamodel.itop-incident-mgmt-itil.xml
  datamodels/2.x/itop-knownerror-mgmt/datamodel.itop-knownerror-mgmt.xml
  datamodels/2.x/itop-oauth-client/datamodel.itop-oauth-client.xml
  datamodels/2.x/itop-problem-mgmt/datamodel.itop-problem-mgmt.xml
  datamodels/2.x/itop-request-mgmt-itil/datamodel.itop-request-mgmt-itil.xml
  datamodels/2.x/itop-request-mgmt/datamodel.itop-request-mgmt.xml
  datamodels/2.x/itop-service-mgmt-provider/datamodel.itop-service-mgmt-provider.xml
  datamodels/2.x/itop-service-mgmt/datamodel.itop-service-mgmt.xml
  datamodels/2.x/itop-storage-mgmt/datamodel.itop-storage-mgmt.xml
  datamodels/2.x/itop-structure/datamodel.itop-structure.xml
  datamodels/2.x/itop-tickets/datamodel.itop-tickets.xml
  datamodels/2.x/itop-virtualization-mgmt/datamodel.itop-virtualization-mgmt.xml
  setup/itopdesignformat.class.inc.php
  sources/Application/UI/Links/Direct/BlockDirectLinkSetViewTable.php
  sources/Application/UI/Links/Indirect/BlockIndirectLinkSetViewTable.php
  tests/php-unit-tests/unitary-tests/setup/iTopDesignFormat/Convert-samples/3.0_to_3.1.expected.xml
  tests/php-unit-tests/unitary-tests/setup/iTopDesignFormat/Convert-samples/3.0_to_3.1.input.xml
  tests/php-unit-tests/unitary-tests/setup/iTopDesignFormat/Convert-samples/3.1_to_3.0.expected.xml
  tests/php-unit-tests/unitary-tests/setup/iTopDesignFormat/Convert-samples/3.1_to_3.0.input.xml
Labels: core, internal
