Repository Combodo/iTop, pull requests merged in 2023-04, with the labels that each got.

#450 N°6173 \HTMLSanitizer::Sanitize : Fix handling only svg_sanitizer
  core/htmlsanitizer.class.inc.php
Labels: internal

#303 🐛 N°6174 Attachments to host objects without org_id can not be downloaded from the portal
  datamodels/2.x/itop-portal-base/portal/src/Controller/ObjectController.php
Labels: security, API

#353 N°6100 ObjectFormManager::OnSubmit : better log for DBWrite exceptions
  datamodels/2.x/itop-portal-base/portal/src/Form/ObjectFormManager.php
Labels: enhancement, internal, supportability

#441 N°6099 DeadLockLog : improve documentation
  core/log.class.inc.php
  tests/php-unit-tests/unitary-tests/core/CMDBSource/DeadLockInjection.php
Labels: internal

#452 N°541 - Dashlets: Improve readability when to much labels (pie chart) or too long labels (bar chart)
  application/displayblock.class.inc.php
Labels: enhancement, internal

#478 N°6179 - Tooltip attribute in field component (in Twig)
  sources/Application/UI/Base/Component/Field/Field.php
  sources/Application/UI/Base/Component/Field/FieldUIBlockFactory.php
  templates/base/components/field/layout.html.twig
Labels: UI, internal

#483 On link modal creation, make ext key to current object readonly, but still submit its value
  application/cmdbabstract.class.inc.php
  application/ui.extkeywidget.class.inc.php
  application/ui.linksdirectwidget.class.inc.php
  lib/autoload.php
  lib/composer/ClassLoader.php
  lib/composer/autoload_classmap.php
  lib/composer/autoload_files.php
  lib/composer/autoload_namespaces.php
  lib/composer/autoload_psr4.php
  lib/composer/autoload_real.php
  lib/composer/autoload_static.php
  lib/composer/include_paths.php
  sources/Application/Helper/FormHelper.php
  sources/Application/Helper/LegacyFormHelper.php
  sources/Controller/Base/Layout/ObjectController.php
  sources/Controller/Links/LinkSetController.php
Labels: internal

#481 N°4010 - Configuration file overwritten with test configuration file
  datamodels/2.x/itop-config/config.php
  datamodels/2.x/itop-config/dictionaries/en.dict.itop-config.php
  datamodels/2.x/itop-config/dictionaries/fr.dict.itop-config.php
Labels: internal

#486 N°6154 N°6219 - Relations Read - tooltip, confirmation title and message
  application/cmdbabstract.class.inc.php
  application/displayblock.class.inc.php
  core/attributedef.class.inc.php
  dictionaries/ui/application/links/en.dictionary.itop.links.php
  dictionaries/ui/application/links/fr.dictionary.itop.links.php
  js/links/links_view_table_widget.js
  js/links/linkset-worker.js
  js/links/linkset.js
  js/object/object-worker.js
  js/pages/backoffice/toolbox.js
  lib/autoload.php
  lib/composer/ClassLoader.php
  lib/composer/autoload_classmap.php
  lib/composer/autoload_files.php
  lib/composer/autoload_namespaces.php
  lib/composer/autoload_psr4.php
  lib/composer/autoload_real.php
  lib/composer/autoload_static.php
  lib/composer/include_paths.php
  lib/composer/installed.php
  sources/Application/UI/Base/Component/DataTable/DataTableUIBlockFactory.php
  sources/Application/UI/Links/AbstractBlockLinkSetViewTable.php
  sources/Application/UI/Links/Direct/BlockDirectLinkSetViewTable.php
  sources/Application/UI/Links/Indirect/BlockIndirectLinkSetViewTable.php
  sources/Controller/AjaxRenderController.php
  sources/Controller/Base/Layout/ObjectController.php
  sources/Controller/Links/LinkSetController.php
  templates/base/components/datatable/row-actions/handler.js.twig
Labels: internal

#487 N°5916 - Generic message on Link Uniqueness rules
  core/dbobject.class.php
  dictionaries/core/uniqueness-rule/en.dictionary.itop.uniqueness-rule.php
  dictionaries/core/uniqueness-rule/fr.dictionary.itop.uniqueness-rule.php
Labels: core, internal
