Repository Combodo/iTop, pull requests merged in 2023-02, with the labels that each got.

#440 N°5904 - Use attribute linked set edit mode to enable actions
  application/cmdbabstract.class.inc.php
  application/ui.extkeywidget.class.inc.php
  js/links/link_set_worker.js
  js/links/links_direct_widget.js
  js/links/links_set.js
  js/links/links_set_worker.js
  js/links/links_view_table_widget.js
  js/links/links_widget.js
  js/objects/objects_worker.js
  js/selectize/plugin_combodo_multi_values_synthesis.js
  js/selectize/plugin_combodo_update_operations.js
  lib/composer/installed.php
  pages/UniversalSearch.php
  pages/tagadmin.php
  sources/Application/UI/Base/Component/Input/Set/Set.php
  sources/Application/UI/Links/AbstractBlockLinksViewTable.php
  sources/Application/UI/Links/Direct/BlockDirectLinksEditTable.php
  sources/Application/UI/Links/Direct/BlockDirectLinksViewTable.php
  sources/Application/UI/Links/Indirect/BlockIndirectLinksEditTable.php
  sources/Application/UI/Links/Indirect/BlockIndirectLinksViewTable.php
  sources/Application/UI/Links/Set/LinksSetUIBlockFactory.php
  sources/Application/WebPage/iTopWebPage.php
  sources/Controller/Base/Layout/ObjectController.php
  sources/Controller/Links/LinksetController.php
  sources/Service/Base/ObjectRepository.php
  templates/application/links/layout.ready.js.twig
  templates/base/components/datatable/config/layout.html.twig
  templates/base/components/input/set/layout.ready.js.twig
Labels: internal

#443 Feature/5932
  application/displayblock.class.inc.php
  dictionaries/ui/application/links/en.dictionary.itop.links.php
  dictionaries/ui/application/links/fr.dictionary.itop.links.php
  sources/Application/UI/Links/Direct/BlockDirectLinksEditTable.php
  sources/Application/UI/Links/Direct/BlockDirectLinksViewTable.php
  sources/Application/UI/Links/Indirect/BlockIndirectLinksEditTable.php
  sources/Application/UI/Links/Indirect/BlockIndirectLinksViewTable.php
  sources/Service/Links/LinkSetModel.php
Labels: internal

#444 N°3190 - Add XML version migration for new AttributeLinkedSet[Indirect] <display_style> tag
  setup/itopdesignformat.class.inc.php
  tests/php-unit-tests/unitary-tests/setup/iTopDesignFormat/Convert-samples/3.1_to_3.0.expected.xml
  tests/php-unit-tests/unitary-tests/setup/iTopDesignFormat/Convert-samples/3.1_to_3.0.input.xml
Labels: internal

#389 N°2783 - Add support for custom zlists
  setup/compiler.class.inc.php
  setup/itopdesignformat.class.inc.php
  tests/php-unit-tests/unitary-tests/setup/iTopDesignFormat/Convert-samples/3.1_to_3.0.expected.xml
  tests/php-unit-tests/unitary-tests/setup/iTopDesignFormat/Convert-samples/3.1_to_3.0.input.xml
Labels: enhancement, core, datamodel, internal

#356 N°6014 Validation pattern for URL : now handles commas in params
  core/attributedef.class.inc.php
  core/config.class.inc.php
  tests/php-unit-tests/unitary-tests/core/AttributeURLTest.php
Labels: bug, internal

#355 N°6016 MissingDependencyException : better text message
  setup/modulediscovery.class.inc.php
Labels: enhancement, internal, supportability, Setup

#449 N°6023 Fix cannot load SVG files in AttributeImage since 3.0.0
  core/htmlsanitizer.class.inc.php
  tests/php-unit-tests/unitary-tests/core/sanitizer/SvgDOMSanitizerTest.php
Labels: bug, internal

#375 N°5603 - Autocomplete fails with error for an external key pointing to an abstract class with no friendlyname
  core/valuesetdef.class.inc.php
  tests/php-unit-tests/unitary-tests/core/MockValueSetObjects.php
  tests/php-unit-tests/unitary-tests/core/ValueSetObjectsTest.php
Labels: bug, internal

#382 N°2916 - Import of IPv6 addresses fails when reconciliation is done on the ip
  core/bulkchange.class.inc.php
Labels: internal

#390 N°5893 - Log triggers exception in CRUD stack
  core/dbobject.class.php
  core/trigger.class.inc.php
Labels: API, internal, supportability
