Repository Combodo/iTop, pull requests merged in 2023-09, with the labels that each got.

#545 5491 brokenui dictformat
  core/dict.class.inc.php
  dictionaries/hu.dictionary.itop.core.php
  dictionaries/hu.dictionary.itop.ui.php
  dictionaries/ja.dictionary.itop.core.php
  dictionaries/ja.dictionary.itop.ui.php
  dictionaries/ru.dictionary.itop.core.php
  dictionaries/sk.dictionary.itop.ui.php
  dictionaries/tr.dictionary.itop.core.php
  tests/php-unit-tests/integration-tests/DictionariesConsistencyAfterSetupTest.php
  tests/php-unit-tests/src/BaseTestCase/ItopTestCase.php
Labels: bug, core, UI, internal

#525 N°6600 Portal download attachment : don't display anymore SQL query on attachment not found error
  core/metamodel.class.php
  datamodels/2.x/itop-portal-base/portal/src/Controller/ObjectController.php
Labels: enhancement, internal

#542 N°6695 Handle multiline dict entries in portal tooltips
  datamodels/2.x/itop-portal-base/portal/public/css/portal.css
  datamodels/2.x/itop-portal-base/portal/public/css/portal.scss
Labels: bug, UI, internal

#548 N°6766 - Fix dependent fields not updated due to WizardHelper.UpdateFields() being triggered too early
  application/wizardhelper.class.inc.php
  js/wizardhelper.js
  pages/ajax.render.php
Labels: internal
