Repository Combodo/iTop, pull requests merged in 2023-08, with the labels that each got.

#531 N°6618 - Fix crash due to router's cache containing an integer instead of an array
  sources/Service/Router/Router.php
  tests/php-unit-tests/unitary-tests/sources/Service/Router/RouterTest.php
Labels: bug, core, internal

#524 🌐 N°6641 - Improve czech translations
  datamodels/2.x/combodo-backoffice-darkmoon-theme/dictionaries/cs.dict.combodo-backoffice-darkmoon-theme.php
  datamodels/2.x/itop-portal-base/dictionaries/cs.dict.itop-portal-base.php
  dictionaries/cs.dictionary.itop.core.php
  dictionaries/cs.dictionary.itop.ui.php
Labels: translation

#523 N°3441 - Portal: Fix failure to open an object containing a link to an archived object
  sources/Renderer/Bootstrap/FieldRenderer/BsSelectObjectFieldRenderer.php
Labels: bug

#457 N°6097 - Enable PHP unit tests on a custom DataModel
  tests/php-unit-tests/composer.json
  tests/php-unit-tests/src/BaseTestCase/ItopCustomDatamodelTestCase.php
  tests/php-unit-tests/src/BaseTestCase/ItopDataTestCase.php
  tests/php-unit-tests/src/Hook/TestsRunStartHook.php
  tests/php-unit-tests/src/Service/UnitTestRunTimeEnvironment.php
  tests/php-unit-tests/unitary-tests/core/TestGLA/TestGLA2Test.delta.xml
  tests/php-unit-tests/unitary-tests/core/TestGLA/TestGLA2Test.php
  tests/php-unit-tests/unitary-tests/core/TestGLA/TestGLATest.delta.xml
  tests/php-unit-tests/unitary-tests/core/TestGLA/TestGLATest.php
Labels: enhancement, internal, modernization, tests

#358 N°4494 - Fix auto-locking on log save and transition
  js/layouts/activity-panel/activity-panel.js
Labels: bug, internal

#467 N°5136 - Relations: Fix "Select All objects" adding obsolete objects even if "show obsolete data" param. not activated
  pages/ajax.render.php
Labels: bug, internal

#530 N°5145 - Fix attachments missing in new ticket when clone from an old ticket with object copier
  datamodels/2.x/itop-attachments/main.itop-attachments.php
Labels: internal
