Repository Combodo/iTop, pull requests merged in 2023-12, with the labels that each got.

#582 N°7055 - Apply better default value for portal copy object link
  datamodels/2.x/itop-portal-base/dictionaries/cs.dict.itop-portal-base.php
  datamodels/2.x/itop-portal-base/dictionaries/da.dict.itop-portal-base.php
  datamodels/2.x/itop-portal-base/dictionaries/de.dict.itop-portal-base.php
  datamodels/2.x/itop-portal-base/dictionaries/en.dict.itop-portal-base.php
  datamodels/2.x/itop-portal-base/dictionaries/es_cr.dict.itop-portal-base.php
  datamodels/2.x/itop-portal-base/dictionaries/fr.dict.itop-portal-base.php
  datamodels/2.x/itop-portal-base/dictionaries/hu.dict.itop-portal-base.php
  datamodels/2.x/itop-portal-base/dictionaries/it.dict.itop-portal-base.php
  datamodels/2.x/itop-portal-base/dictionaries/ja.dict.itop-portal-base.php
  datamodels/2.x/itop-portal-base/dictionaries/nl.dict.itop-portal-base.php
  datamodels/2.x/itop-portal-base/dictionaries/pl.dict.itop-portal-base.php
  datamodels/2.x/itop-portal-base/dictionaries/pt_br.dict.itop-portal-base.php
  datamodels/2.x/itop-portal-base/dictionaries/ru.dict.itop-portal-base.php
  datamodels/2.x/itop-portal-base/dictionaries/sk.dict.itop-portal-base.php
  datamodels/2.x/itop-portal-base/dictionaries/tr.dict.itop-portal-base.php
  datamodels/2.x/itop-portal-base/dictionaries/zh_cn.dict.itop-portal-base.php
Labels: enhancement

#579 N°7021 - Fix error log and useless compilation time due to SCSS file unnecessary compilation
  sources/Application/WebPage/NiceWebPage.php
Labels: bug, internal

#588 N°7059 - Symfony 6.4 - Application skeleton - sources registration
  app.php
  application/cmdbabstract.class.inc.php
  core/csvbulkexport.class.inc.php
  core/pdfbulkexport.class.inc.php
  lib/composer/autoload_classmap.php
  lib/composer/autoload_static.php
  lib/composer/installed.php
  pages/ajax.csvimport.php
  pages/csvimport.php
  pages/preferences.php
  sources/Application/UI/Base/Component/DataTable/DataTable.php
  sources/Application/UI/Base/Component/DataTable/DataTableConfig/DataTableConfig.php
  sources/Application/UI/Base/Component/GlobalSearch/GlobalSearch.php
  sources/Application/UI/Base/Component/Input/Select/SelectUIBlockFactory.php
  sources/Application/UI/Base/Component/QuickCreate/QuickCreate.php
  sources/Application/UI/Base/Layout/ActivityPanel/ActivityPanelFactory.php
  sources/Application/UI/Base/Layout/ActivityPanel/CaseLogEntryForm/CaseLogEntryFormFactory.php
  sources/Application/UI/Base/Layout/NavigationMenu/NavigationMenu.php
  sources/Application/UI/Base/Layout/Object/ObjectDetails.php
  sources/Application/UI/Hook/iKeyboardShortcut.php
  sources/Application/UI/Links/Set/BlockLinkSetDisplayAsProperty.php
  sources/Application/UI/Links/Set/LinkSetUIBlockFactory.php
  sources/Core/Authentication/Client/Smtp/Oauth.php
  sources/Core/Email/EmailFactory.php
  sources/Core/Email/EmailLaminas.php
  sources/Kernel.php
  sources/Renderer/Console/FieldRenderer/ConsoleSelectObjectFieldRenderer.php
  sources/Renderer/Console/FieldRenderer/ConsoleSimpleFieldRenderer.php
  symfony/config/services.yaml
  webservices/export-v2.php
Labels: core, internal, modernization

#540 N°7067 - Add setting to change default "password change" URL
  application/loginform.class.inc.php
  core/config.class.inc.php
Labels: enhancement, good first issue

#556 N°6816 - Search: Fix JS "me._onACSearchContainsSuccess is not a function" error
  js/search/search_form_criteria_enum.js
Labels: bug, internal

#591 N°6889 - Don't force TCP protocol anymore on localhost without port
  core/cmdbsource.class.inc.php
  setup/backup.class.inc.php
  tests/php-unit-tests/unitary-tests/core/CMDBSource/CMDBSourceTest.php
  tests/php-unit-tests/unitary-tests/setup/DBBackupTest.php
Labels: bug, internal

#584 N°7077 Hungarian translations based on iTop 3.0.2-1
  README.md
  datamodels/2.x/authent-cas/dictionaries/hu.dict.authent-cas.php
  datamodels/2.x/authent-ldap/dictionaries/hu.dict.authent-ldap.php
  datamodels/2.x/authent-local/dictionaries/hu.dict.authent-local.php
  datamodels/2.x/combodo-backoffice-darkmoon-theme/dictionaries/hu.dict.combodo-backoffice-darkmoon-theme.php
  datamodels/2.x/combodo-db-tools/dictionaries/hu.dict.combodo-db-tools.php
  datamodels/2.x/itop-attachments/dictionaries/hu.dict.itop-attachments.php
  datamodels/2.x/itop-backup/dictionaries/hu.dict.itop-backup.php
  datamodels/2.x/itop-bridge-cmdb-ticket/dictionaries/hu.dict.itop-bridge-cmdb-ticket.php
  datamodels/2.x/itop-change-mgmt-itil/dictionaries/hu.dict.itop-change-mgmt-itil.php
  datamodels/2.x/itop-change-mgmt/dictionaries/hu.dict.itop-change-mgmt.php
  datamodels/2.x/itop-config-mgmt/dictionaries/hu.dict.itop-config-mgmt.php
  datamodels/2.x/itop-config/dictionaries/hu.dict.itop-config.php
  datamodels/2.x/itop-core-update/dictionaries/hu.dict.itop-core-update.php
  datamodels/2.x/itop-faq-light/dictionaries/hu.dict.itop-faq-light.php
  datamodels/2.x/itop-files-information/dictionaries/hu.dict.itop-files-information.php
  datamodels/2.x/itop-hub-connector/dictionaries/hu.dict.itop-hub-connector.php
  datamodels/2.x/itop-incident-mgmt-itil/dictionaries/hu.dict.itop-incident-mgmt-itil.php
  datamodels/2.x/itop-knownerror-mgmt/dictionaries/hu.dict.itop-knownerror-mgmt.php
  datamodels/2.x/itop-oauth-client/hu.dict.itop-oauth-client.php
  datamodels/2.x/itop-portal-base/dictionaries/hu.dict.itop-portal-base.php
  datamodels/2.x/itop-portal/dictionaries/hu.dict.itop-portal.php
  datamodels/2.x/itop-problem-mgmt/dictionaries/hu.dict.itop-problem-mgmt.php
  datamodels/2.x/itop-request-mgmt-itil/dictionaries/hu.dict.itop-request-mgmt-itil.php
  datamodels/2.x/itop-request-mgmt/dictionaries/hu.dict.itop-request-mgmt.php
  datamodels/2.x/itop-service-mgmt-provider/dictionaries/hu.dict.itop-service-mgmt-provider.php
  datamodels/2.x/itop-service-mgmt/dictionaries/hu.dict.itop-service-mgmt.php
  datamodels/2.x/itop-structure/dictionaries/hu.dict.itop-structure.php
  datamodels/2.x/itop-themes-compat/hu.dict.itop-themes-compat.php
  datamodels/2.x/itop-tickets/dictionaries/hu.dict.itop-tickets.php
  dictionaries/hu.dictionary.itop.core.php
  dictionaries/hu.dictionary.itop.ui.php
  dictionaries/ui/components/breadcrumbs/hu.dictionary.itop.breadcrumbs.php
  dictionaries/ui/components/datatable/hu.dictionary.itop.datatable.php
  dictionaries/ui/components/field/hu.dictionary.itop.field.php
  dictionaries/ui/components/global-search/hu.dictionary.itop.global-search.php
  dictionaries/ui/components/input/hu.dictionary.itop.input.php
  dictionaries/ui/components/quick-create/hu.dictionary.itop.quick-create.php
  dictionaries/ui/layouts/activity-panel/hu.dictionary.itop.activity-panel.php
  dictionaries/ui/layouts/navigation-menu/hu.dictionary.itop.navigation-menu.php
  dictionaries/ui/layouts/object-details/hu.dictionary.itop.object-details.php
  dictionaries/ui/layouts/page-content/hu.dictionary.itop.page-content.php
  dictionaries/ui/layouts/tab-container/hu.dictionary.itop.tab-container.php
  dictionaries/ui/layouts/ui-content-block/hu.dictionary.itop.ui-content-block.php
  dictionaries/ui/pages/errorpage/hu.dictionary.itop.errorpage.php
  dictionaries/ui/pages/preferences/hu.dictionary.itop.preferences.php
Labels: translation

#501 N°7082 Possibility to not only force synchronous sending of e-mails, but also asynchronous sending
  core/email.class.inc.php
  sources/Core/Email/EmailLaminas.php
Labels: enhancement
