Repository Combodo/iTop, pull requests merged in 2023-01, with the labels that each got.

#383 N°5841 - Non-admin managing User can't see Administrator by default
  core/config.class.inc.php
Labels: internal

#330 N°1350 - Audit improvements
  application/application.inc.php
  application/audit.category.class.inc.php
  application/audit.domain.class.inc.php
  core/autoload.php
  core/config.class.inc.php
  dictionaries/de.dictionary.itop.ui.php
  dictionaries/en.dictionary.itop.ui.php
  lib/composer/ClassLoader.php
  lib/composer/autoload_classmap.php
  lib/composer/autoload_real.php
  lib/composer/autoload_static.php
  pages/audit.php
Labels: enhancement

#286 N°5867 Display binary data size in SynchroReplica details
  synchro/synchrodatasource.class.inc.php
Labels: UI

#378 N°3136 - Add creation and modification of n-n objects in object details
  application/cmdbabstract.class.inc.php
  application/displayblock.class.inc.php
  css/backoffice/components/_alert.scss
  css/backoffice/components/_modal.scss
  css/backoffice/layout/tab-container/_tab-container.scss
  css/backoffice/utils/mixins/_all.scss
  css/backoffice/utils/mixins/_highlight.scss
  dictionaries/ui/application/links/en.dictionary.itop.links.php
  dictionaries/ui/components/modal/en.dictionary.itop.modal.php
  js/links/link_set_worker.js
  js/pages/backoffice/toolbox.js
  js/utils.js
  pages/UI.php
  sources/Application/UI/Base/Component/DataTable/DataTable.php
  sources/Application/UI/Base/Component/DataTable/DataTableUIBlockFactory.php
  sources/Application/UI/Links/AbstractBlockLinksViewTable.php
  sources/Application/UI/Links/Indirect/BlockIndirectLinksViewTable.php
  sources/Application/WebPage/iTopWebPage.php
  sources/Controller/Base/Layout/ObjectController.php
  sources/Controller/Links/LinksetController.php
  templates/base/components/datatable/layout.ready.js.twig
Labels: internal

#385 N°3300 - Add creation and modification of 1-n objects in object details
  sources/Application/UI/Base/Component/DataTable/DataTableUIBlockFactory.php
  sources/Application/UI/Links/Direct/BlockDirectLinksViewTable.php
  sources/Controller/Links/LinksetController.php
Labels: internal

#392 N°5914 - Wrong encoding in modules configuration editor
  datamodels/2.x/itop-config/config.php
Labels: internal

#393 N°5920 - Add linkset's description as corresponding tab's tooltip in object details
  application/cmdbabstract.class.inc.php
  css/backoffice/layout/tab-container/_tab-container.scss
  datamodels/2.x/combodo-backoffice-darkmoon-theme/precompiled-themes/main.css
  datamodels/2.x/itop-structure/precompiled-themes/fullmoon/main.css
  datamodels/2.x/itop-structure/precompiled-themes/test-red/main.css
  sources/Application/UI/Base/Layout/TabContainer/Tab/AjaxTab.php
  sources/Application/UI/Base/Layout/TabContainer/Tab/Tab.php
  sources/Application/UI/Base/Layout/TabContainer/TabContainer.php
  sources/Application/WebPage/AjaxPage.php
  sources/Application/WebPage/TabManager.php
  sources/Application/WebPage/iTopWebPage.php
  templates/base/layouts/tab-container/layout.html.twig
Labels: internal

#416 Feature/5825 -Links friendlynames & uniqueness
  datamodels/2.x/itop-bridge-cmdb-ticket/datamodel.itop-bridge-cmdb-ticket.xml
  datamodels/2.x/itop-bridge-cmdb-ticket/dictionaries/en.dict.itop-bridge-cmdb-ticket.php
  datamodels/2.x/itop-bridge-virtualization-storage/datamodel.itop-bridge-virtualization-storage.xml
  datamodels/2.x/itop-config-mgmt/datamodel.itop-config-mgmt.xml
  datamodels/2.x/itop-config-mgmt/dictionaries/en.dict.itop-config-mgmt.php
  datamodels/2.x/itop-knownerror-mgmt/datamodel.itop-knownerror-mgmt.xml
  datamodels/2.x/itop-knownerror-mgmt/dictionaries/en.dict.itop-knownerror-mgmt.php
  datamodels/2.x/itop-service-mgmt-provider/datamodel.itop-service-mgmt-provider.xml
  datamodels/2.x/itop-service-mgmt-provider/dictionaries/en.dict.itop-service-mgmt-provider.php
  datamodels/2.x/itop-service-mgmt/datamodel.itop-service-mgmt.xml
  datamodels/2.x/itop-service-mgmt/dictionaries/en.dict.itop-service-mgmt.php
  datamodels/2.x/itop-storage-mgmt/datamodel.itop-storage-mgmt.xml
  datamodels/2.x/itop-structure/datamodel.itop-structure.xml
  datamodels/2.x/itop-tickets/datamodel.itop-tickets.xml
  datamodels/2.x/itop-tickets/dictionaries/en.dict.itop-tickets.php
  datamodels/2.x/itop-tickets/dictionaries/fr.dict.itop-tickets.php
Labels: internal

#439 N°5929 - Update hungarian translations on authent-local thanks to @tacsaby #438
  datamodels/2.x/authent-local/dictionaries/hu.dict.authent-local.php
Labels: translation

#384 N°5849 - Fix wrong encoding of external keys in "Header with statstics" dashlet
  application/displayblock.class.inc.php
Labels: internal

#438 N°5929 - Update hungarian translations thanks to @tacsaby
  datamodels/2.x/authent-cas/dictionaries/hu.dict.authent-cas.php
  datamodels/2.x/authent-local/dictionaries/hu.dict.authent-local.php
  datamodels/2.x/combodo-db-tools/dictionaries/hu.dict.combodo-db-tools.php
  datamodels/2.x/itop-attachments/dictionaries/hu.dict.itop-attachments.php
  datamodels/2.x/itop-backup/dictionaries/hu.dict.itop-backup.php
  datamodels/2.x/itop-bridge-cmdb-ticket/dictionaries/hu.dict.itop-bridge-cmdb-ticket.php
  datamodels/2.x/itop-change-mgmt-itil/dictionaries/hu.dict.itop-change-mgmt-itil.php
  datamodels/2.x/itop-change-mgmt/dictionaries/hu.dict.itop-change-mgmt.php
  datamodels/2.x/itop-config-mgmt/dictionaries/hu.dict.itop-config-mgmt.php
  datamodels/2.x/itop-config/dictionaries/hu.dict.itop-config.php
  datamodels/2.x/itop-core-update/dictionaries/hu.dict.itop-core-update.php
  datamodels/2.x/itop-faq-light/dictionaries/hu.dict.itop-faq-light.php
  datamodels/2.x/itop-files-information/dictionaries/hu.dict.itop-files-information.php
  datamodels/2.x/itop-hub-connector/dictionaries/hu.dict.itop-hub-connector.php
  datamodels/2.x/itop-incident-mgmt-itil/dictionaries/hu.dict.itop-incident-mgmt-itil.php
  datamodels/2.x/itop-knownerror-mgmt/dictionaries/hu.dict.itop-knownerror-mgmt.php
  datamodels/2.x/itop-oauth-client/hu.dict.itop-oauth-client.php
  datamodels/2.x/itop-portal-base/dictionaries/hu.dict.itop-portal-base.php
  datamodels/2.x/itop-portal/dictionaries/hu.dict.itop-portal.php
  datamodels/2.x/itop-problem-mgmt/dictionaries/hu.dict.itop-problem-mgmt.php
  datamodels/2.x/itop-request-mgmt-itil/dictionaries/hu.dict.itop-request-mgmt-itil.php
  datamodels/2.x/itop-request-mgmt/dictionaries/hu.dict.itop-request-mgmt.php
  datamodels/2.x/itop-service-mgmt-provider/dictionaries/hu.dict.itop-service-mgmt-provider.php
  datamodels/2.x/itop-service-mgmt/dictionaries/hu.dict.itop-service-mgmt.php
  datamodels/2.x/itop-structure/dictionaries/hu.dict.itop-structure.php
  datamodels/2.x/itop-themes-compat/hu.dict.itop-themes-compat.php
  datamodels/2.x/itop-tickets/dictionaries/hu.dict.itop-tickets.php
  dictionaries/hu.dictionary.itop.core.php
  dictionaries/ui/components/breadcrumbs/hu.dictionary.itop.breadcrumbs.php
  dictionaries/ui/components/datatable/hu.dictionary.itop.datatable.php
  dictionaries/ui/components/field/hu.dictionary.itop.field.php
  dictionaries/ui/components/global-search/hu.dictionary.itop.global-search.php
  dictionaries/ui/components/input/hu.dictionary.itop.input.php
  dictionaries/ui/components/quick-create/hu.dictionary.itop.quick-create.php
  dictionaries/ui/layouts/activity-panel/hu.dictionary.itop.activity-panel.php
  dictionaries/ui/layouts/navigation-menu/hu.dictionary.itop.navigation-menu.php
  dictionaries/ui/layouts/object-details/hu.dictionary.itop.object-details.php
  dictionaries/ui/layouts/page-content/hu.dictionary.itop.page-content.php
  dictionaries/ui/layouts/tab-container/hu.dictionary.itop.tab-container.php
  dictionaries/ui/layouts/ui-content-block/hu.dictionary.itop.ui-content-block.php
  dictionaries/ui/pages/errorpage/hu.dictionary.itop.errorpage.php
  dictionaries/ui/pages/preferences/hu.dictionary.itop.preferences.php
Labels: translation
