Repository Combodo/iTop, pull requests merged in 2023-05, with the labels that each got.

#489 Feature/6154 - Confirmation modal issue
  js/pages/backoffice/toolbox.js
  templates/base/components/datatable/row-actions/handler.js.twig
Labels: internal

#490 Feature/6154 - Change dict key
  core/attributedef.class.inc.php
  dictionaries/core/uniqueness-rule/fr.dictionary.itop.uniqueness-rule.php
  js/pages/backoffice/toolbox.js
  sources/Application/UI/Links/AbstractBlockLinkSetViewTable.php
  sources/Controller/Links/LinkSetController.php
Labels: internal

#488 N°6265 - Too many call to current person in database
  core/metamodel.class.php
Labels: core, internal

#376 N°5559 - Prevent obsolete replica to lock iTop object
  application/cmdbabstract.class.inc.php
  core/config.class.inc.php
  core/dbobject.class.php
Labels: bug, internal

#477 N°6133 - Add extra files to backup and restore
  datamodels/2.x/itop-backup/dbrestore.class.inc.php
  setup/backup.class.inc.php
  tests/php-unit-tests/unitary-tests/setup/DBBackupDataTest.php
Labels: enhancement, internal
