Repository Combodo/iTop, pull requests merged in 2024-11, with the labels that each got.

#672 :bug: N°7916 SF#2274 EmailLaminas.php: Keep charset with part header in multipart email
  sources/Core/Email/EmailLaminas.php
  tests/php-unit-tests/unitary-tests/core/EMailTest.php
Labels: bug

#678 :globe_with_meridians: Translations - Fix some Typos in English translations
  datamodels/2.x/authent-ldap/dictionaries/en.dict.authent-ldap.php
  datamodels/2.x/combodo-db-tools/dictionaries/en.dict.combodo-db-tools.php
  datamodels/2.x/itop-config-mgmt/dictionaries/en.dict.itop-config-mgmt.php
  datamodels/2.x/itop-incident-mgmt-itil/dictionaries/en.dict.itop-incident-mgmt-itil.php
  datamodels/2.x/itop-oauth-client/dictionaries/en.dict.itop-oauth-client.php
  datamodels/2.x/itop-portal-base/dictionaries/en.dict.itop-portal-base.php
  datamodels/2.x/itop-request-mgmt-itil/dictionaries/en.dict.itop-request-mgmt-itil.php
  datamodels/2.x/itop-request-mgmt/dictionaries/en.dict.itop-request-mgmt.php
  datamodels/2.x/itop-service-mgmt-provider/dictionaries/en.dict.itop-service-mgmt-provider.php
  datamodels/2.x/itop-service-mgmt/dictionaries/en.dict.itop-service-mgmt.php
  dictionaries/en.dictionary.itop.core.php
  dictionaries/en.dictionary.itop.ui.php
  dictionaries/ui/layouts/activity-panel/en.dictionary.itop.activity-panel.php
  dictionaries/ui/layouts/page-content/en.dictionary.itop.page-content.php
Labels: translation

#673 N°1000 - Portal: filter BrowseBrick result varies if in list or tree
  datamodels/2.x/itop-portal-base/portal/public/css/portal.css
  datamodels/2.x/itop-portal-base/portal/public/css/portal.scss
  datamodels/2.x/itop-portal-base/portal/public/lib/jquery-treelistfilter/js/TreeListFilter.js
  datamodels/2.x/itop-portal-base/portal/src/Helper/BrowseBrickHelper.php
  datamodels/2.x/itop-portal-base/portal/templates/bricks/browse/mode_tree.html.twig
Labels: internal

#676 ⚡️ Add faster way to rename column on the same table
  setup/moduleinstaller.class.inc.php
  tests/php-unit-tests/unitary-tests/setup/ModuleInstallerAPITest.php
Labels: API, Performance, Setup

#652 Correctly identify as iTop in cURL requests
  application/utils.inc.php
  core/config.class.inc.php
Labels: enhancement

#681 N°7219 - Dashboard issue (fix 2.7)
  application/dashboard.class.inc.php
Labels: bug, internal

#687 Issue/7707
  core/datamodel.core.xml
  dictionaries/cs.dictionary.itop.core.php
  dictionaries/da.dictionary.itop.core.php
  dictionaries/de.dictionary.itop.core.php
  dictionaries/en.dictionary.itop.core.php
  dictionaries/es_cr.dictionary.itop.core.php
  dictionaries/fr.dictionary.itop.core.php
  dictionaries/hu.dictionary.itop.core.php
  dictionaries/it.dictionary.itop.core.php
  dictionaries/ja.dictionary.itop.core.php
  dictionaries/nl.dictionary.itop.core.php
  dictionaries/pl.dictionary.itop.core.php
  dictionaries/pt_br.dictionary.itop.core.php
  dictionaries/ru.dictionary.itop.core.php
  dictionaries/sk.dictionary.itop.core.php
  dictionaries/tr.dictionary.itop.core.php
  dictionaries/zh_cn.dictionary.itop.core.php
  pages/preferences.php
  sources/Controller/Newsroom/iTopNewsroomController.php
Labels: internal
