Repository Combodo/iTop, pull requests merged in 2024-02, with the labels that each got.

#532 N°6619 - Attachment : Make contact_id an AttributeExternalKey instead of AttributeExternalField
  datamodels/2.x/itop-attachments/datamodel.itop-attachments.xml
  datamodels/2.x/itop-attachments/module.itop-attachments.php
Labels: internal

#460 N°7068 - Add emulation for apc_exists function
  core/apc-emulation.php
Labels: bug

#583 N°7052 synchro_import.php: fix undefined offset notices
  synchro/synchro_import.php
Labels: bug, internal

#549 N°5472 Notification Action objects : add a last executions tab
  core/action.class.inc.php
  core/config.class.inc.php
  dictionaries/en.dictionary.itop.core.php
  lib/composer/autoload_classmap.php
  lib/composer/autoload_static.php
  sources/Controller/Notifications/ActionController.php
Labels: enhancement, internal

#605 N°7179 Remove unused var in ActionEmail::PrepareMessageContent
  core/action.class.inc.php
Labels: internal

#609 N°7244 Fix setup ContextTag init
  setup/applicationinstaller.class.inc.php
  setup/wizardcontroller.class.inc.php
Labels: enhancement, internal, Setup

#606 N°7245 Add details on exceptions in RunTimeEnvironment::CallInstallerHandlers
  setup/runtimeenv.class.inc.php
Labels: enhancement, internal, Setup

#608 N°7213 - PHP 8.1: Migrate remaining usages of md5() with null value
  core/attributedef.class.inc.php
  core/ormdocument.class.inc.php
Labels: bug, core, internal

#607 N°7212 - PHP 8.1: Migrate remaining usages of strlen() with null value
  core/ormcaselog.class.inc.php
Labels: bug, core, internal

#614 N°7243 - Add toast notifications to iTop
  css/backoffice/components/_all.scss
  css/backoffice/components/_toast.scss
  css/backoffice/vendors/_all.scss
  css/backoffice/vendors/_toastify.scss
  dictionaries/ui/pages/preferences/en.dictionary.itop.preferences.php
  js/pages/backoffice/toolbox.js
  js/utils.js
  node_modules/.package-lock.json
  node_modules/toastify-js/.gitattributes
  node_modules/toastify-js/.prettierrc
  node_modules/toastify-js/.travis.yml
  node_modules/toastify-js/CHANGELOG.md
  node_modules/toastify-js/LICENSE
  node_modules/toastify-js/README.md
  node_modules/toastify-js/example/pattern.png
  node_modules/toastify-js/example/script.css
  node_modules/toastify-js/example/script.js
  node_modules/toastify-js/index.html
  node_modules/toastify-js/package.json
  node_modules/toastify-js/src/toastify-es.js
  node_modules/toastify-js/src/toastify.css
  node_modules/toastify-js/src/toastify.js
  package-lock.json
  package.json
  pages/preferences.php
  sources/Application/WebPage/iTopWebPage.php
Labels: UI, internal

#578 N°7008 - Fix missing background tasks in CRON when autoloaded and NOT in "developer_mode"
  webservices/cron.php
Labels: bug, core, internal

#620 N°7288 - Fix page crash due to unescaped characters in relations row actions
  templates/base/components/datatable/row-actions/handler.js.twig
Labels: bug, internal

#616 N°7163 - Avoid having an empty list when "items per page" is set to 0 as it makes no sense
  css/backoffice/components/datatable/_datatableconfig.scss
  js/dataTables.settings.js
  sources/Controller/AjaxRenderController.php
  templates/base/components/datatable/config/layout.html.twig
Labels: bug, internal

#521 N°6543 - Fix display of AttributeText with width parameter
  application/ui.htmleditorwidget.class.inc.php
  core/attributedef.class.inc.php
  css/backoffice/components/_field.scss
  css/backoffice/components/datatable/_datatable.scss
Labels: internal

#529 N°5547 - Object deletion fails if friendlyname too long
  core/cmdbobject.class.inc.php
  tests/php-unit-tests/unitary-tests/core/CMDBObjectTest.php
  tests/php-unit-tests/unitary-tests/core/DBObjectTest.php
Labels: internal

#617 N°2039 - Rework view all notifications page
  core/datamodel.core.xml
  css/backoffice/_shame.scss
  css/backoffice/components/_panel.scss
  css/backoffice/components/input/_all.scss
  css/backoffice/components/input/_input-toggler.scss
  css/backoffice/layout/_top-bar.scss
  css/backoffice/layout/object/_object-summary.scss
  css/backoffice/pages/_all.scss
  css/backoffice/pages/_notifications.scss
  css/backoffice/utils/mixins/_all.scss
  css/backoffice/utils/mixins/_selectable.scss
  css/backoffice/utils/variables/_spacing.scss
  css/backoffice/utils/variables/_typography.scss
  dictionaries/ui/application/newsroom/en.dictionary.itop.newsroom.php
  dictionaries/ui/application/newsroom/fr.dictionary.itop.newsroom.php
  images/illustrations/undraw_social_serenity.svg
  js/pages/backoffice/itop-newsroom.view-all.js
  lib/composer/autoload_classmap.php
  lib/composer/autoload_static.php
  sources/Application/UI/Base/Component/ButtonGroup/ButtonGroup.php
  sources/Application/UI/Base/Component/Input/InputUIBlockFactory.php
  sources/Application/UI/Base/Component/Input/InputWithLabel.php
  sources/Application/UI/Base/Component/Input/Toggler.php
  sources/Application/UI/Base/Component/PopoverMenu/NewsroomMenu/NewsroomMenuFactory.php
  sources/Application/UI/Base/Layout/Object/ObjectDetails.php
  sources/Application/UI/Base/Layout/Object/ObjectSummary.php
  sources/Controller/Newsroom/iTopNewsroomController.php
  sources/Service/Notification/NotificationsRepository.php
  templates/base/components/input/input-toggler.html.twig
  templates/base/components/input/input-toggler.ready.js.twig
Labels: enhancement, UI, internal

#321 N°4342 - Improve generic bulk deletion function with memory limit handling
  core/config.class.inc.php
  core/metamodel.class.php
  tests/php-unit-tests/unitary-tests/core/MetaModelTest.php
Labels: question, internal

#522 N°3363 - Add favicon in branding
  application/loginwebpage.class.inc.php
  datamodels/2.x/itop-portal-base/portal/src/DependencyInjection/SilexCompatBootstrap/PortalXmlConfiguration/Basic.php
  datamodels/2.x/itop-portal-base/portal/templates/layout.html.twig
  setup/compiler.class.inc.php
  setup/itopdesignformat.class.inc.php
  sources/Application/Branding.php
  sources/Application/WebPage/UnauthenticatedWebPage.php
  sources/Application/WebPage/WebPage.php
  tests/php-unit-tests/unitary-tests/setup/iTopDesignFormat/Convert-samples/3.1_to_3.2.expected.xml
  tests/php-unit-tests/unitary-tests/setup/iTopDesignFormat/Convert-samples/3.1_to_3.2.input.xml
  tests/php-unit-tests/unitary-tests/setup/iTopDesignFormat/Convert-samples/3.2_to_3.1.expected.xml
  tests/php-unit-tests/unitary-tests/setup/iTopDesignFormat/Convert-samples/3.2_to_3.1.input.xml
  tests/php-unit-tests/unitary-tests/setup/iTopDesignFormat/iTopDesignFormatTest.php
Labels: internal

#539 N°5170 - In a transition DoCheckToWrite returned error, generes a Fatal error
  application/cmdbabstract.class.inc.php
  datamodels/2.x/itop-portal-base/portal/src/Form/ObjectFormManager.php
  datamodels/2.x/itop-portal-base/portal/src/Helper/ObjectFormHandlerHelper.php
  pages/UI.php
Labels: internal

#575 N°6968 - Audit duration : add of a rule multiplie by 4 the time of response
  core/dbsearch.class.php
  core/userrights.class.inc.php
  pages/audit.php
  tests/php-unit-tests/unitary-tests/core/DBSearchTest.php
Labels: internal
