Repository Combodo/iTop, pull requests merged in 2024-01, with the labels that each got.

#598 N°4368 Fix CORB blocking regression
  application/ajaxwebpage.class.inc.php
  application/webpage.class.inc.php
  application/xmlpage.class.inc.php
  core/config.class.inc.php
Labels: bug, internal

#597 N°7130 - Allows to ignore existing column field in setup's data migration method
  setup/moduleinstaller.class.inc.php
  tests/php-unit-tests/unitary-tests/setup/ModuleInstallerAPITest.php
Labels: API, Setup

#595 N°2039 - Update Chinese translations for the newsroom
  dictionaries/en.dictionary.itop.core.php
  dictionaries/zh_cn.dictionary.itop.core.php
Labels: translation

#551 N°7137 - DataSynchro: Remove "Organization" as default value for SynchroReplica->dest_class
  synchro/synchrodatasource.class.inc.php
Labels: bug

#592 N°7085 - Fix infinite loop in login page until fatal error occurs
  application/logindefault.class.inc.php
  core/config.class.inc.php
  tests/php-unit-tests/unitary-tests/application/LoginTest.php
Labels: bug, core, internal

#528 N°3448 - Framework field size check not correctly implemented for multibytes languages/strings
  core/dbobject.class.php
  core/displayablegraph.class.inc.php
  core/event.class.inc.php
  synchro/synchrodatasource.class.inc.php
  tests/php-unit-tests/unitary-tests/core/DBObjectTest.php
  tests/php-unit-tests/unitary-tests/core/EventIssueTest.php
  webservices/webservices.class.inc.php
Labels: bug, core, internal

#555 N°6648 - Use \utils::GetDataPath() instead of hard-coded paths
  application/excelexporter.class.inc.php
  application/transaction.class.inc.php
  core/bulkexport.class.inc.php
  core/dbsearch.class.php
  core/simplegraph.class.inc.php
  datamodels/2.x/itop-backup/ajax.backup.php
  datamodels/2.x/itop-backup/dbrestore.class.inc.php
  datamodels/2.x/itop-backup/main.itop-backup.php
  datamodels/2.x/itop-backup/status.php
  datamodels/2.x/itop-core-update/src/Service/CoreUpdater.php
  datamodels/2.x/itop-hub-connector/ajax.php
  datamodels/2.x/itop-hub-connector/hubnewsroomprovider.class.inc.php
  datamodels/2.x/itop-hub-connector/land.php
  datamodels/2.x/itop-hub-connector/launch.php
  pages/exec.php
  pages/graphviz.php
  setup/applicationinstaller.class.inc.php
  setup/backup.class.inc.php
  setup/runtimeenv.class.inc.php
  setup/setuputils.class.inc.php
  setup/wizardsteps.class.inc.php
  setup/xmldataloader.class.inc.php
  sources/Controller/AjaxRenderController.php
  tests/php-unit-tests/legacy-tests/replay_query_log.php
  tests/php-unit-tests/src/Hook/TestsRunStartHook.php
Labels: enhancement, internal

#601 N°7147 - Error HTTP 500 due to access_token not URL decoded
  sources/Application/TwigBase/Controller/Controller.php
  tests/php-unit-tests/unitary-tests/application/twigbase/ControllerTest.php
  tests/php-unit-tests/unitary-tests/application/twigbase/FakeController.php
Labels: internal

#604 N°7172 HTML markup for n:n set properties
  application/cmdbabstract.class.inc.php
Labels: internal
