Repository Combodo/iTop, pull requests merged in 2024-03, with the labels that each got.

#625 N°2039 N°7298 - Allow Actions to be asynchronous
  core/action.class.inc.php
  core/asynctask.class.inc.php
  core/config.class.inc.php
  core/datamodel.core.xml
  dictionaries/cs.dictionary.itop.core.php
  dictionaries/da.dictionary.itop.core.php
  dictionaries/de.dictionary.itop.core.php
  dictionaries/en.dictionary.itop.core.php
  dictionaries/es_cr.dictionary.itop.core.php
  dictionaries/fr.dictionary.itop.core.php
  dictionaries/hu.dictionary.itop.core.php
  dictionaries/it.dictionary.itop.core.php
  dictionaries/ja.dictionary.itop.core.php
  dictionaries/nl.dictionary.itop.core.php
  dictionaries/pl.dictionary.itop.core.php
  dictionaries/pt_br.dictionary.itop.core.php
  dictionaries/ru.dictionary.itop.core.php
  dictionaries/sk.dictionary.itop.core.php
  dictionaries/tr.dictionary.itop.core.php
  dictionaries/zh_cn.dictionary.itop.core.php
  lib/composer/autoload_classmap.php
  lib/composer/autoload_static.php
  sources/Service/Notification/Event/EventiTopNotificationService.php
  tests/php-unit-tests/unitary-tests/core/ActionEmailTest.php
Labels: enhancement, internal

#248 N°4894 - Improve AttributeDecimal validation during CSV import
  core/attributedef.class.inc.php
Labels: enhancement, API

#615 N°7343 Catch ParseError when loading dict files in setup
  setup/modelfactory.class.inc.php
Labels: enhancement, internal, supportability

#626 N°7302 Fix unit name in \SetupUtils::HumanReadableSize
  setup/setuputils.class.inc.php
Labels: bug, internal

#618 N°7345 Accept DateTime objects for DBObject::Set() calls on AttributeDateTime and children
  core/attributedef.class.inc.php
  core/dbobject.class.php
  tests/php-unit-tests/unitary-tests/core/DBObjectTest.php
  tests/php-unit-tests/unitary-tests/webservices/ImportTest.php
Labels: enhancement, core, internal

#632 N°7336 DeprecatedCallsLog robustness
  core/log.class.inc.php
  tests/php-unit-tests/unitary-tests/core/Log/DeprecatedCallsLogTest.php
Labels: bug, internal

#603 N°6974 - Flatten classes in datamodel
  core/designdocument.class.inc.php
  js/icon_select.js
  lib/autoload.php
  lib/composer/ClassLoader.php
  lib/composer/autoload_classmap.php
  lib/composer/autoload_files.php
  lib/composer/autoload_namespaces.php
  lib/composer/autoload_psr4.php
  lib/composer/autoload_real.php
  lib/composer/autoload_static.php
  lib/composer/include_paths.php
  setup/itopdesignformat.class.inc.php
  setup/modelfactory.class.inc.php
  tests/php-unit-tests/unitary-tests/setup/ModelFactoryTest.php
  tests/php-unit-tests/unitary-tests/setup/iTopDesignFormat/Convert-samples/1.7_to_3.0.expected.xml
  tests/php-unit-tests/unitary-tests/setup/iTopDesignFormat/Convert-samples/1.7_to_3.0.input.xml
Labels: core, datamodel, internal

#613 N°7194 - Add link to datamodel class schema on object details
  application/menunode.class.inc.php
  css/backoffice/layout/object/_object-details.scss
  dictionaries/ui/layouts/object-details/cs.dictionary.itop.object-details.php
  dictionaries/ui/layouts/object-details/da.dictionary.itop.object-details.php
  dictionaries/ui/layouts/object-details/de.dictionary.itop.object-details.php
  dictionaries/ui/layouts/object-details/en.dictionary.itop.object-details.php
  dictionaries/ui/layouts/object-details/es_cr.dictionary.itop.object-details.php
  dictionaries/ui/layouts/object-details/fr.dictionary.itop.object-details.php
  dictionaries/ui/layouts/object-details/hu.dictionary.itop.object-details.php
  dictionaries/ui/layouts/object-details/it.dictionary.itop.object-details.php
  dictionaries/ui/layouts/object-details/ja.dictionary.itop.object-details.php
  dictionaries/ui/layouts/object-details/nl.dictionary.itop.object-details.php
  dictionaries/ui/layouts/object-details/pl.dictionary.itop.object-details.php
  dictionaries/ui/layouts/object-details/pt_br.dictionary.itop.object-details.php
  dictionaries/ui/layouts/object-details/ru.dictionary.itop.object-details.php
  dictionaries/ui/layouts/object-details/sk.dictionary.itop.object-details.php
  dictionaries/ui/layouts/object-details/tr.dictionary.itop.object-details.php
  dictionaries/ui/layouts/object-details/zh_cn.dictionary.itop.object-details.php
  sources/Application/TwigBase/Twig/Extension.php
  templates/base/layouts/object/object-details/layout.html.twig
Labels: enhancement, internal

#519 N°7292 - Improve Clear function in ExtKeyWidget
  js/extkeywidget.js
Labels: internal

#624 Bring unattended-install CLI script in iTop repository
  setup/unattended-install/.htaccess
  setup/unattended-install/README.md
  setup/unattended-install/unattended-install.php
  setup/unattended-install/web.config
  tests/php-unit-tests/unitary-tests/setup/unattended-install/UnattendedInstallTest.php
Labels: enhancement
