Repository Combodo/iTop, pull requests merged in 2024-04, with the labels that each got.

#643 N°7416 - Setup: Add warning for optionnal PHP extension "APCu"
  composer.json
  setup/setuputils.class.inc.php
Labels: Performance, internal, supportability

#547 N°6964 - Add API to allow modules to register files to include in the backup
  application/applicationextension.inc.php
  setup/backup.class.inc.php
  tests/php-unit-tests/unitary-tests/application/applicationextension/ApplicationExtensionTest.php
  tests/php-unit-tests/unitary-tests/application/applicationextension/Delta/application-extension-usages-in-snippets.xml
Labels: enhancement

#572 N°6962 - Impact analysis does not fully take into account the user rights with sharing base
  core/config.class.inc.php
  core/relationgraph.class.inc.php
  tests/php-unit-tests/unitary-tests/core/RelationGraphTest.php
Labels: internal

#645 N°2443 - Boolean don't accept yes/no value
  application/cmdbabstract.class.inc.php
  core/attributedef.class.inc.php
Labels: bug, core, internal

#505 N°6167 - API for the content of the Welcome Popup
  application/applicationextension.inc.php
  application/datamodel.application.xml
  application/templates/welcome_popup.html
  css/backoffice/application/_all.scss
  css/backoffice/application/welcome-popup/_all.scss
  css/backoffice/application/welcome-popup/_welcome-popup.scss
  css/backoffice/pages/_all.scss
  css/backoffice/pages/_welcome-popup.scss
  css/setup.css
  dictionaries/cs.dictionary.itop.ui.php
  dictionaries/da.dictionary.itop.ui.php
  dictionaries/de.dictionary.itop.ui.php
  dictionaries/en.dictionary.itop.ui.php
  dictionaries/es_cr.dictionary.itop.ui.php
  dictionaries/fr.dictionary.itop.ui.php
  dictionaries/hu.dictionary.itop.ui.php
  dictionaries/it.dictionary.itop.ui.php
  dictionaries/ja.dictionary.itop.ui.php
  dictionaries/nl.dictionary.itop.ui.php
  dictionaries/pl.dictionary.itop.ui.php
  dictionaries/pt_br.dictionary.itop.ui.php
  dictionaries/ru.dictionary.itop.ui.php
  dictionaries/sk.dictionary.itop.ui.php
  dictionaries/tr.dictionary.itop.ui.php
  dictionaries/ui/application/welcome-popup/cs.dictionary.itop.welcome-popup.php
  dictionaries/ui/application/welcome-popup/da.dictionary.itop.welcome-popup.php
  dictionaries/ui/application/welcome-popup/de.dictionary.itop.welcome-popup.php
  dictionaries/ui/application/welcome-popup/en.dictionary.itop.welcome-popup.php
  dictionaries/ui/application/welcome-popup/es_cr.dictionary.itop.welcome-popup.php
  dictionaries/ui/application/welcome-popup/fr.dictionary.itop.welcome-popup.php
  dictionaries/ui/application/welcome-popup/hu.dictionary.itop.welcome-popup.php
  dictionaries/ui/application/welcome-popup/it.dictionary.itop.welcome-popup.php
  dictionaries/ui/application/welcome-popup/ja.dictionary.itop.welcome-popup.php
  dictionaries/ui/application/welcome-popup/nl.dictionary.itop.welcome-popup.php
  dictionaries/ui/application/welcome-popup/pl.dictionary.itop.welcome-popup.php
  dictionaries/ui/application/welcome-popup/pt_br.dictionary.itop.welcome-popup.php
  dictionaries/ui/application/welcome-popup/ru.dictionary.itop.welcome-popup.php
  dictionaries/ui/application/welcome-popup/sk.dictionary.itop.welcome-popup.php
  dictionaries/ui/application/welcome-popup/tr.dictionary.itop.welcome-popup.php
  dictionaries/ui/application/welcome-popup/zh_cn.dictionary.itop.welcome-popup.php
  dictionaries/zh_cn.dictionary.itop.ui.php
  images/welcome.jpg
  lib/composer/autoload_classmap.php
  lib/composer/autoload_static.php
  pages/UI.php
  pages/ajax.render.php
  sources/Application/WelcomePopup/Message.php
  sources/Application/WelcomePopup/MessageFactory.php
  sources/Application/WelcomePopup/Provider/DefaultProvider.php
  sources/Application/WelcomePopup/WelcomePopupService.php
  sources/Controller/WelcomePopupController.php
  templates/application/welcome_popup/layout.html.twig
  templates/application/welcome_popup/layout.ready.js.twig
  templates/application/welcome_popup/templates/layout.html.twig
  templates/application/welcome_popup/templates/left-illustration-right-title-description.html.twig
  templates/application/welcome_popup/templates/left-title-description-right-illustration.html.twig
  templates/pages/backoffice/welcome_popup/welcome_popup.html.twig
  templates/pages/backoffice/welcome_popup/welcome_popup.ready.js.twig
  tests/php-unit-tests/unitary-tests/application/WelcomePopup/WelcomePopupTest.php
Labels: internal

#627 :bug: N°7313 - Bad display of single quotes in charts
  application/displayblock.class.inc.php
  tests/php-unit-tests/composer.json
  tests/php-unit-tests/src/Service/UnitTestRunTimeEnvironment.php
  tests/php-unit-tests/unitary-tests/application/DisplayBlock/Delta/add-enum-value-with-quote.xml
  tests/php-unit-tests/unitary-tests/application/DisplayBlock/DisplayBlockTest.php
  tests/php-unit-tests/unitary-tests/application/applicationextension/Delta/application-extension-usages-in-snippets.xml
Labels: bug, internal
