Repository Combodo/iTop, pull requests merged in 2024-07, with the labels that each got.

#600 N°7645 - PHP 8.1: Fix usage of strpos() & str_replace() with null value when compiling empty dictionary
  setup/compiler.class.inc.php
Labels: bug, Setup

#646 N°7644 - Add Brand logo and Model picture
  datamodels/2.x/itop-config-mgmt/datamodel.itop-config-mgmt.xml
  datamodels/2.x/itop-config-mgmt/dictionaries/en.dict.itop-config-mgmt.php
Labels: enhancement

#653 🌐 N°7652 - Update italian translations
  dictionaries/it.dictionary.itop.core.php
  dictionaries/it.dictionary.itop.ui.php
Labels: translation

#648 N°7397 - Update welcome popup content for iTop 3.2
  css/backoffice/application/welcome-popup/_welcome-popup.scss
  dictionaries/ui/application/welcome-popup/cs.dictionary.itop.welcome-popup.php
  dictionaries/ui/application/welcome-popup/da.dictionary.itop.welcome-popup.php
  dictionaries/ui/application/welcome-popup/de.dictionary.itop.welcome-popup.php
  dictionaries/ui/application/welcome-popup/en.dictionary.itop.welcome-popup.php
  dictionaries/ui/application/welcome-popup/es_cr.dictionary.itop.welcome-popup.php
  dictionaries/ui/application/welcome-popup/fr.dictionary.itop.welcome-popup.php
  dictionaries/ui/application/welcome-popup/hu.dictionary.itop.welcome-popup.php
  dictionaries/ui/application/welcome-popup/it.dictionary.itop.welcome-popup.php
  dictionaries/ui/application/welcome-popup/ja.dictionary.itop.welcome-popup.php
  dictionaries/ui/application/welcome-popup/nl.dictionary.itop.welcome-popup.php
  dictionaries/ui/application/welcome-popup/pl.dictionary.itop.welcome-popup.php
  dictionaries/ui/application/welcome-popup/pt_br.dictionary.itop.welcome-popup.php
  dictionaries/ui/application/welcome-popup/ru.dictionary.itop.welcome-popup.php
  dictionaries/ui/application/welcome-popup/sk.dictionary.itop.welcome-popup.php
  dictionaries/ui/application/welcome-popup/tr.dictionary.itop.welcome-popup.php
  dictionaries/ui/application/welcome-popup/zh_cn.dictionary.itop.welcome-popup.php
  images/illustrations/undraw_designer_mindset.svg
  images/illustrations/undraw_new_notifications.svg
  images/illustrations/undraw_newspaper.svg
  images/illustrations/undraw_preferences_popup.svg
  sources/Application/TwigBase/Twig/Extension.php
  sources/Application/WelcomePopup/MessageFactory.php
  sources/Application/WelcomePopup/Provider/DefaultProvider.php
  templates/application/welcome_popup/templates/layout.html.twig
  templates/application/welcome_popup/templates/left-illustration-as-svg-markup-right-title-description.html.twig
  templates/application/welcome_popup/templates/left-title-description-right-illustration-as-svg-markup.html.twig
Labels: enhancement, internal

#657 🌐 N°7686 - Updated Dutch translations for iTop 3.2
  datamodels/2.x/authent-ldap/dictionaries/nl.dict.authent-ldap.php
  datamodels/2.x/combodo-db-tools/dictionaries/nl.dict.combodo-db-tools.php
  datamodels/2.x/itop-attachments/dictionaries/nl.dict.itop-attachments.php
  datamodels/2.x/itop-backup/dictionaries/nl.dict.itop-backup.php
  datamodels/2.x/itop-bridge-cmdb-services/dictionaries/nl.dict.itop-bridge-cmdb-services.php
  datamodels/2.x/itop-bridge-cmdb-ticket/dictionaries/nl.dict.itop-bridge-cmdb-ticket.php
  datamodels/2.x/itop-config-mgmt/dictionaries/nl.dict.itop-config-mgmt.php
  datamodels/2.x/itop-config/dictionaries/nl.dict.itop-config.php
  datamodels/2.x/itop-core-update/dictionaries/nl.dict.itop-core-update.php
  datamodels/2.x/itop-files-information/dictionaries/nl.dict.itop-files-information.php
  datamodels/2.x/itop-knownerror-mgmt/dictionaries/nl.dict.itop-knownerror-mgmt.php
  datamodels/2.x/itop-oauth-client/dictionaries/nl.dict.itop-oauth-client.php
  datamodels/2.x/itop-portal/dictionaries/nl.dict.itop-portal.php
  datamodels/2.x/itop-request-mgmt-itil/dictionaries/nl.dict.itop-request-mgmt-itil.php
  datamodels/2.x/itop-request-mgmt/dictionaries/nl.dict.itop-request-mgmt.php
  datamodels/2.x/itop-service-mgmt-provider/dictionaries/nl.dict.itop-service-mgmt-provider.php
  datamodels/2.x/itop-service-mgmt/dictionaries/nl.dict.itop-service-mgmt.php
  datamodels/2.x/itop-structure/dictionaries/nl.dict.itop-structure.php
  datamodels/2.x/itop-themes-compat/dictionaries/nl.dict.itop-themes-compat.php
  datamodels/2.x/itop-tickets/dictionaries/nl.dict.itop-tickets.php
  dictionaries/core/orm-value/orm-document/nl.dictionary.itop.orm-document.php
  dictionaries/core/uniqueness-rule/nl.dictionary.itop.uniqueness-rule.php
  dictionaries/nl.dictionary.itop.core.php
  dictionaries/nl.dictionary.itop.ui.php
  dictionaries/ui/components/datatable/nl.dictionary.itop.datatable.php
  dictionaries/ui/components/input/nl.dictionary.itop.input.php
  dictionaries/ui/layouts/object-details/nl.dictionary.itop.object-details.php
Labels: translation

#659 N°7646 - Check performances compared to beginning of 3.2 development
  datamodels/2.x/itop-portal-base/portal/src/Helper/ContextManipulatorHelper.php
Labels: Performance, internal, OQL

#623 N°7697 - Add method to rename DB table during setup
  setup/moduleinstaller.class.inc.php
  tests/php-unit-tests/unitary-tests/setup/ModuleInstallerAPITest.php
Labels: enhancement, core

#656 :globe_with_meridians: N°7687 Update German translations for iTop 3.2
  datamodels/2.x/itop-oauth-client/dictionaries/de.dict.itop-oauth-client.php
  datamodels/2.x/itop-portal/dictionaries/de.dict.itop-portal.php
  dictionaries/de.dictionary.itop.core.php
  dictionaries/de.dictionary.itop.ui.php
  dictionaries/ui/application/bulk/de.dictionary.itop.bulk.php
  dictionaries/ui/application/object/de.dictionary.itop.object.php
  dictionaries/ui/application/welcome-popup/de.dictionary.itop.welcome-popup.php
  dictionaries/ui/components/input/de.dictionary.itop.input.php
  dictionaries/ui/layouts/object-details/de.dictionary.itop.object-details.php
  dictionaries/ui/pages/preferences/de.dictionary.itop.preferences.php
Labels: translation
