Repository Combodo/iTop, pull requests merged in 2025-01, with the labels that each got.

#695 N°7383 Show data table even when there is no data after filtering
  datamodels/2.x/itop-portal-base/portal/templates/bricks/manage/layout-table.html.twig
Labels: internal

#696 N°8031 - Make all portal bricks use custom templates for all templates
  datamodels/2.x/itop-portal-base/portal/config/packages/cache.yaml
  datamodels/2.x/itop-portal-base/portal/src/Brick/AbstractBrick.php
  datamodels/2.x/itop-portal-base/portal/src/Brick/AggregatePageBrick.php
  datamodels/2.x/itop-portal-base/portal/src/Brick/BrickCollection.php
  datamodels/2.x/itop-portal-base/portal/src/Brick/BrowseBrick.php
  datamodels/2.x/itop-portal-base/portal/src/Brick/CreateBrick.php
  datamodels/2.x/itop-portal-base/portal/src/Brick/FilterBrick.php
  datamodels/2.x/itop-portal-base/portal/src/Brick/ManageBrick.php
  datamodels/2.x/itop-portal-base/portal/src/Brick/ObjectBrick.php
  datamodels/2.x/itop-portal-base/portal/src/Brick/PortalBrick.php
  datamodels/2.x/itop-portal-base/portal/src/Brick/UserProfileBrick.php
  datamodels/2.x/itop-portal-base/portal/src/Controller/AbstractController.php
  datamodels/2.x/itop-portal-base/portal/src/Controller/AggregatePageBrickController.php
  datamodels/2.x/itop-portal-base/portal/src/Controller/BrowseBrickController.php
  datamodels/2.x/itop-portal-base/portal/src/Controller/CreateBrickController.php
  datamodels/2.x/itop-portal-base/portal/src/Controller/DefaultController.php
  datamodels/2.x/itop-portal-base/portal/src/Controller/ManageBrickController.php
  datamodels/2.x/itop-portal-base/portal/src/Controller/ObjectController.php
  datamodels/2.x/itop-portal-base/portal/src/Controller/UserProfileBrickController.php
  datamodels/2.x/itop-portal-base/portal/src/DataCollector/PortalCollector.php
  datamodels/2.x/itop-portal-base/portal/src/DependencyInjection/SilexCompatBootstrap/PortalXmlConfiguration/Basic.php
  datamodels/2.x/itop-portal-base/portal/src/Service/TemplatesProvider/TemplateDefinitionDto.php
  datamodels/2.x/itop-portal-base/portal/src/Service/TemplatesProvider/TemplatesProviderInterface.php
  datamodels/2.x/itop-portal-base/portal/src/Service/TemplatesProvider/TemplatesProviderService.php
  datamodels/2.x/itop-portal-base/portal/src/Service/TemplatesProvider/TemplatesRegister.php
  datamodels/2.x/itop-portal-base/portal/src/Twig/TemplatesTwigExtension.php
  datamodels/2.x/itop-portal-base/portal/templates/bricks/aggregate-page/layout.html.twig
  datamodels/2.x/itop-portal-base/portal/templates/bricks/browse/layout.html.twig
  datamodels/2.x/itop-portal-base/portal/templates/bricks/browse/mode_list.html.twig
  datamodels/2.x/itop-portal-base/portal/templates/bricks/browse/mode_mosaic.html.twig
  datamodels/2.x/itop-portal-base/portal/templates/bricks/browse/mode_tree.html.twig
  datamodels/2.x/itop-portal-base/portal/templates/bricks/create/modal.html.twig
  datamodels/2.x/itop-portal-base/portal/templates/bricks/layout.html.twig
  datamodels/2.x/itop-portal-base/portal/templates/bricks/manage/layout-chart.html.twig
  datamodels/2.x/itop-portal-base/portal/templates/bricks/manage/layout-table.html.twig
  datamodels/2.x/itop-portal-base/portal/templates/bricks/manage/layout.html.twig
  datamodels/2.x/itop-portal-base/portal/templates/bricks/manage/tile-chart.html.twig
  datamodels/2.x/itop-portal-base/portal/templates/bricks/manage/tile-top-list.html.twig
  datamodels/2.x/itop-portal-base/portal/templates/bricks/object/layout.html.twig
  datamodels/2.x/itop-portal-base/portal/templates/bricks/object/modal.html.twig
  datamodels/2.x/itop-portal-base/portal/templates/bricks/object/mode_apply_stimulus.html.twig
  datamodels/2.x/itop-portal-base/portal/templates/bricks/object/mode_edit.html.twig
  datamodels/2.x/itop-portal-base/portal/templates/bricks/object/mode_view.html.twig
  datamodels/2.x/itop-portal-base/portal/templates/bricks/user-profile/layout.html.twig
  datamodels/2.x/itop-portal-base/portal/templates/data_collector/portal.html.twig
  datamodels/2.x/itop-portal-base/portal/vendor/autoload.php
  datamodels/2.x/itop-portal-base/portal/vendor/composer/autoload_classmap.php
  datamodels/2.x/itop-portal-base/portal/vendor/composer/autoload_real.php
  datamodels/2.x/itop-portal-base/portal/vendor/composer/autoload_static.php
  datamodels/2.x/itop-portal-base/portal/vendor/composer/installed.php
  datamodels/2.x/itop-portal/datamodel.itop-portal.xml
  sources/Service/InterfaceDiscovery/InterfaceDiscovery.php
Labels: internal

#697 🌐 Italian translation enhancements
  datamodels/2.x/itop-config-mgmt/dictionaries/it.dict.itop-config-mgmt.php
  datamodels/2.x/itop-config/dictionaries/it.dict.itop-config.php
  datamodels/2.x/itop-knownerror-mgmt/dictionaries/it.dict.itop-knownerror-mgmt.php
  datamodels/2.x/itop-portal/dictionaries/it.dict.itop-portal.php
  datamodels/2.x/itop-problem-mgmt/dictionaries/it.dict.itop-problem-mgmt.php
  datamodels/2.x/itop-request-mgmt-itil/dictionaries/it.dict.itop-request-mgmt-itil.php
  dictionaries/it.dictionary.itop.core.php
  dictionaries/it.dictionary.itop.ui.php
Labels: translation

#699 N°8113 Fix global organization filter
  sources/Application/UI/Base/Layout/NavigationMenu/NavigationMenu.php
Labels: internal

#636 N°7371 - Remembers the choice done in the popup that appears when saving public and private logs at the same time
  js/layouts/activity-panel/activity-panel.js
  js/utils.js
  sources/Application/UI/Base/Layout/ActivityPanel/ActivityPanel.php
  templates/base/layouts/activity-panel/layout.js.twig
Labels: bug, internal
